### ISSUE TITLE
[Feature request] Black theme

### ISSUE THREAD

**Issue by Primokorn** [helloworld1/FreeOTPPlus#1]
Hi,
AFAIR there's no black theme in the original app but could you have a look?
Thank you.

**Comment by helloworld1** [comment]
Yea, sounds good

**Comment by helloworld1** [comment]
Finally refactored some theming logic. Dark theme will be possible in the near future. Sorry for the delay.

**Comment by helloworld1** [comment]
Dark theme is implemented in this commit:
11e759ab719d1f1f9cbb64fd30ad97fd38472828
