### ISSUE TITLE
Change extension for exported txt file

### ISSUE THREAD

**Issue by mattcen** [helloworld1/FreeOTPPlus#101]
When exporting with the "Export JSON format", the file is appropriately named `freeotp-backup.json`. When exporting with "Export key URI format", the file is named `freeotp-backup.txt.json`. I suspect this is because the [code](https://github.com/helloworld1/FreeOTPPlus/blob/master/app/src/main/java/org/fedorahosted/freeotp/ui/MainActivity.kt#L171) says:

```kt
createFile("application/json", "freeotp-backup.txt", WRITE_KEY_URI_REQUEST_CODE)
```

Note the 'application/json' for what is essentially a text file. Perhaps creating this file as 'text/plain' or similar would remedy this needless 'json' extension?

**Comment by helloworld1** [comment]
Yes, this is definitely a bug and needs to be fixed using text/plain mime type.

**Comment by helloworld1** [comment]
The issue is fixed in https://github.com/helloworld1/FreeOTPPlus/commit/5918c90cd449f55c774842cbaf1e1728fda333b6
