### ISSUE TITLE
Autolock

### ISSUE THREAD

**Issue by Minoru** [helloworld1/FreeOTPPlus#103]
Ideally, FreeOTP+ shouldn't stay unlocked for long: I can forget I unlocked it, then hand the phone to someone who will be able to see my list of tokens and generate codes. Here's some ideas that FreeOTP+ could borrow from KeePassDX (a password manager):

1. "app timeout" -- locks the database after a configurable duration
2. "screen lock" -- locks the database when the screen is off
3. pressing Back while in the main menu locks the database. KeePassDX can have multiple DBs, but for FreeOTP+, it makes sense to quit the app as well.

**Comment by helloworld1** [comment]
Sounds like a good suggestion to lock when the screen is locked.

**Comment by helloworld1** [comment]
Commit https://github.com/helloworld1/FreeOTPPlus/commit/1b320fc7b6997edfad2912fe71fd5baef51d185b was checked in to have 2 minutes timeout when the app is in background.

**Comment by Minoru** [comment]
Awesome, thank you very much!
