### ISSUE TITLE
Preparations for v2.2 release?

### ISSUE THREAD

**Issue by 6543** [helloworld1/FreeOTPPlus#104]
@helloworld1 do you think releasing 2.2 to publish all new&updated translations?

**Comment by helloworld1** [comment]
I will fix a problem of the token icons in dark mode issue. After that I will release a new version with updated translations.

**Comment by helloworld1** [comment]
The background contrast commit was checked in and I am preparing for a release. This commit https://github.com/helloworld1/FreeOTPPlus/commit/e0b503ff0fe6b6caec05f7abc7b01d821d921582  added a new string to allow user to remove an user added token image in the token edit screen. I am checking with you if you want to add the translation for it before the 2.2 release. Thanks!

**Comment by 6543** [comment]
@helloworld1 I'll update translation and let you konw :)
