### ISSUE TITLE
Steam trade verification

### ISSUE THREAD

**Issue by Keraldi** [helloworld1/FreeOTPPlus#108]
Probably out of scope for the project but Steam Guard is used as security measure to accept trades in addition to TOTP.

I've been thinking about implementing it in a cross-platform project (the functionality is currently implemented and provided by https://github.com/winauth/winauth but the project has been archived and it's focussed on windows).

Winauth also provides a sample implementation to request/generate the otp-URI from Steam (which is likely also out of scope for the project).

Anyways, I guess my question is whether or not a PR for it would be accepted.

**Comment by helloworld1** [comment]
Steam guard is supported in FreeOTP+. See https://github.com/helloworld1/FreeOTPPlus/issues/48
But it requires some manual work to add the token. If you have ideas to simplify the process, feel free to comment.

**Comment by Keraldi** [comment]
Yes, I am aware that Steam Guard TOTP is supported, however the trade confirmation notifications are not (as they are not TOTP).
The mentioned project (https://github.com/winauth/winauth) implements a way to both request the secret from Steam (so the Steam app is never required in the first place) as well as the Steam trade confirmation messages that are requires to accept trades on top of a regular TOTP implementation.

Reading the source is pretty straightforward and the project is licensed GPL-3, according to https://www.apache.org/licenses/GPL-compatibility.html, this project's license (Apache 2) is compatible.

Relevant files in the project:
(For the logic)
https://github.com/winauth/winauth/blob/master/Authenticator/SteamAuthenticator.cs (largely irrelevant as it's the Steam Authenticator implementation)
https://github.com/winauth/winauth/blob/master/Authenticator/SteamClient.cs (includes `trade` as keyword a couple times, this should include most, if not all of the logic required for trade confirmations)

(I believe those are just relevant for the UI)
https://github.com/winauth/winauth/blob/master/WinAuth/ShowSteamTradesForm.cs
https://github.com/winauth/winauth/blob/master/WinAuth/ShowSteamTradesForm.designer.cs
https://github.com/winauth/winauth/blob/master/WinAuth/ShowSteamTradesForm.resx
