### ISSUE TITLE
[Question] Importing data from FreeOTP

### ISSUE THREAD

**Issue by akwala** [helloworld1/FreeOTPPlus#11]
FreeOTP doesn't provide a way to export the stored keys. Would it be possible to import the data from FreeOTP into FreeOTP+ using a backup made with Titanium Backup? Any other ways this could be done?

**Comment by helloworld1** [comment]
Yes, I assume you have rooted your phone.  You can "adb" to copy. 
```
adb shell
su
cp /data/data/org.fedorahosted.freeotp/shared_prefs/tokens.xml /data/data/org.liberty.android.freeotpplus/shared_prefs/tokens.xml
```

Titanium Backup may also work but I am not an expert in that.

**Comment by akwala** [comment]
Thanks, @helloworld1

The file got copied -- I viewed it -- but FreeOTP+ says no keys are installed.

**Comment by helloworld1** [comment]
Please force stop FreeOTP+ first and then copy the file again. If you leave the app open, it can overwrite the keys.

**Comment by helloworld1** [comment]
I tried it myself. After force close, the keys will be copied correctly.

**Comment by akwala** [comment]
Not sure I understand... The tokens.xml under organization.liberty.android.freeotpplus _is_ the one I copied, it has my keys. FreeOTP+ doesn't seem to be reading it. Force stopping the app makes no difference.

I also tried copying the file afresh (after renaming the existing one) while FreeOTP+ was force stopped. The app didn't show any keys when launched. What am I missing?

**Comment by akwala** [comment]
Thanks, @helloworld1 ... That worked!

**Comment by gloomytrousers** [comment]
If you have TWRP, you can run @helloworld1's command in recovery via Advanced -> Terminal. No root or ADB required.
