### ISSUE TITLE
yandex yaotp request

### ISSUE THREAD

**Issue by chris-tian78** [helloworld1/FreeOTPPlus#114]
Could you add the Yandex authentication method "yaotp"?

**Comment by helloworld1** [comment]
I actually don't know what it is. Does it conform RFC 6238 TOTP or RFC 4226 HOTP?

**Comment by chris-tian78** [comment]
neither totp, nor hotp. this is a Yandex thing. But there is probably a plugin for keepass. https://github.com/norblik/KeeYaOtp

**Comment by helloworld1** [comment]
Unfortunately I don't think I am able to support an specific authentication method that requires significant amount of work. I will only evaluate if it is a variant of TOTP or HOTP.
