### ISSUE TITLE
Getting keys from storage

### ISSUE THREAD

**Issue by Latrolage** [helloworld1/FreeOTPPlus#115]
My device softbricked, but i have a backup of the storage, is there anything stopping me from copying the keys from that backup to my current installation. Where would the file be to do this, or are the keys obfuscated/encrypted somehow

**Comment by helloworld1** [comment]
I don't know how did you backup your storage. Did you export the keys to a file and stored somewhere? If so, you can retrieve the file and import it to a new installation. The exported key file is not encrypted.
If you only backup the system storage, I don't think you can easily migrated keys to the other device.
