### ISSUE TITLE
Slight lag when loading custom icons

### ISSUE THREAD

**Issue by tkterris** [helloworld1/FreeOTPPlus#116]
When a custom icon (PNG in my testing) is specified, there is a slight delay in loading the icon when opening up the main activity for the first time. The placeholder icon is displayed briefly, before showing the custom icon. This is particularly noticeable when there are several tokens configured using the built-in icons, but one or two with custom icons - the built-in icons load immediately, while the custom icons load after a short (~100-200 ms) delay.

**Comment by helloworld1** [comment]
This is caused by async loading by Picasso library. I am not sure about the cost of preloading of all token image and possibility of blocking the UI thread. If one has a lot of tokens and custom images, it can also run out of ram.

**Comment by tkterris** [comment]
I updated the PR to move the Picasso fetch() call to the IO thread (in a suspend function in ImageUtil). That shouldn't matter though, since the fetch() function is asynchronous. I did some testing by passing in some image URLs from https://deelay.me/ and there's no effect on the UI thread.

Memory usage won't change, token images are already being fetched into memory by setTokenImage. This just changes the order so it's fetched a bit earlier.

**Comment by helloworld1** [comment]
Currently I think the RecyclerView will only load images that is on screen.I am worried if we prefetch, we will fetch all of them

**Comment by tkterris** [comment]
Yeah, you're right. 

For the fetch() call to help, it has to be made before some unrelated operation causing a delay in the UI, so that the image can be fetched in parallel during the delay. It looks like the biggest delay in rendering the MainActivity is from calculating the diff of the ListAdapter, to determine which tokens are rendered. So, if it waits until after the list is calculated so that only the tokens shown on screen have their images fetched (e.g. by putting the fetch call in onCurrentListChanged), then the list is rendered immediately, and the fetch doesn't help. If it fetches beforehand, it wouldn't know which tokens are being rendered, so it would have to fetch all images, like you describe.

I still think it's not a big deal to fetch all images, since in my use case (and I suspect the median use case) there are less than 10 tokens, so the memory overhead of loading all those thumbnails isn't noticeable. So, I'll keep the change on my fork.

**Comment by tkterris** [comment]
Updated the PR, it now only loads a subset (the first 12) token images.

**Comment by helloworld1** [comment]
I found there are still performance problem even pre-fetched when I scroll around. The Picasso library has clearly cached the image already but it takes time to load. I will investigate further into the image performance.

**Comment by helloworld1** [comment]
With commit def8ffe2591731021cf25d282cc441a86b8c59c7 and c97ff2f380446e80ee18f29a2f208ce125bebde6. The image cache loading performance is much better. I don't think we need prefetch anymore. Would you please rebase and test out?
