### ISSUE TITLE
is there a way to migrate my OTP settings from FreeOTP to FreeOTP+?

### ISSUE THREAD

**Issue by lemmy04** [helloworld1/FreeOTPPlus#118]
since FreeOTP has seen quite a few commits but no actual new release....

**Comment by sid-the-sloth** [comment]
Yes, you can easily migrate from old FreeOTP to FreeOTPPlus (no root is needed for your android phone).

See wiki in this repo. There is a link to a script that can convert the extracted tokens.xml to a json file which can then be imported in FreeOTPPlus.

Also, you can read the article here: https://externalmem.wordpress.com/2021/03/05/freeotp-export-secrets-and-migrate-to-freeotpplus/

Hope this helps!

**Comment by lemmy04** [comment]
> Also, you can read the article here: https://externalmem.wordpress.com/2021/03/05/freeotp-export-secrets-and-migrate-to-freeotpplus/

that worked like a charm!
