### ISSUE TITLE
Possible useful script for the wiki

### ISSUE THREAD

**Issue by sid-the-sloth** [helloworld1/FreeOTPPlus#119]
Hi,

Love your project, great job!
I wrote a node js script which help people migrate from FreeOTP to FreeOTPPlus and I thought you might post the URL in the wiki:

https://gitlab.com/sid-the-sloth/conversion-scripts/-/blob/master/freeotp-xml-to-json.js

Feel free to add the file above to your repo here as well -- it's totally free to use and modify (Apache license) :)
Thanks!

**Comment by helloworld1** [comment]
Nicely done! I will add a link to your script.

**Comment by helloworld1** [comment]
I have modified the wiki with a link to your script. Closing this issue. Thanks!
