### ISSUE TITLE
[Feature request / Security Concern] Please encrypt/password protect the backups

### ISSUE THREAD

**Issue by lemmy04** [helloworld1/FreeOTPPlus#122]
When I export my settings the file is plaintext and completely unprotected - if someone managed to get that file from my backup they could steal all tokens most easily.

Suggestion:

Encrypt the backup with a password on export, and prompt for password on import.
Of course the option to import unencrypted should stay around for a few releases as well...

**Comment by helloworld1** [comment]
Let's consolidate the discussion in #128
