### ISSUE TITLE
Service name more readable

### ISSUE THREAD

**Issue by fullcavediver** [helloworld1/FreeOTPPlus#129]
Please make the service name in the app a little bit more readable - maybe the font a little bigger or other colour.
Thank you!

**Comment by helloworld1** [comment]
What about reducing the space between 2fa code and issuer to make issuer slightly bigger? 
Normally the icon is used for distinguish the issuers.

**Comment by fullcavediver** [comment]
That is exactly the point. If you enlarge the font by 2px, the space between 2fa code and issuer will be smaller.

**Comment by helloworld1** [comment]
Fixed in https://github.com/helloworld1/FreeOTPPlus/commit/a0b1ccc898b285b0a9ceb87e23f35a336d57d24b
