### ISSUE TITLE
Import error 

### ISSUE THREAD

**Issue by onos1** [helloworld1/FreeOTPPlus#13]
Expected behavior
After clicking on a document through the import feature, I expected the app to load the document.

Actual behavior
After clicking the document to import the app crashes.

How to reproduce
download the FREEOTPPLUS app https://f-droid.org/repo/org.liberty.android.freeotpplus_1.apk
click on the three dots at the top right corner
click on import
click on any data App crashes
Infinix note 4
Operating system: android 7.0
version 1.0

`04-22 16:51:54.917 11973 12304 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
04-22 16:51:54.917 11973 12304 E AndroidRuntime: Process: org.liberty.android.freeotpplus, PID: 11973
04-22 16:51:54.917 11973 12304 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
04-22 16:51:54.917 11973 12304 E AndroidRuntime:     at android.os.AsyncTask$3.done(AsyncTask.java:318)
04-22 16:51:54.917 11973 12304 E AndroidRuntime:     at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
04-22 16:51:54.917 11973 12304 E AndroidRuntime:     at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
04-22 16:51:54.917 11973 12304 E AndroidRuntime:     at java.util.concurrent.FutureTask.run(FutureTask.java:242)
04-22 16:51:54.917 11973 12304 E AndroidRuntime:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
04-22 16:51:54.917 11973 12304 E AndroidRuntime:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
04-22 16:51:54.917 11973 12304 E AndroidRuntime:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
04-22 16:51:54.917 11973 12304 E AndroidRuntime:     at java.lang.Thread.run(Thread.java:761)
04-22 16:51:54.917 11973 12304 E AndroidRuntime: Caused by: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
04-22 16:51:54.917 11973 12304 E AndroidRuntime:     at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:224)
04-22 16:51:54.917 11973 12304 E AndroidRuntime:     at com.google.gson.Gson.fromJson(Gson.java:887)
04-22 16:51:54.917 11973 12304 E AndroidRuntime:     at com.google.gson.Gson.fromJson(Gson.java:852)
04-22 16:51:54.917 11973 12304 E AndroidRuntime:     at com.google.gson.Gson.fromJson(Gson.java:801)
04-22 16:51:54.917 11973 12304 E AndroidRuntime:     at com.google.gson.Gson.fromJson(Gson.java:773)
04-22 16:51:54.917 11973 12304 E AndroidRuntime:     at org.fedorahosted.freeotp.TokenPersistence.importFromJSON(TokenPersistence.kt:112)
04-22 16:51:54.917 11973 12304 E AndroidRuntime:     at org.fedorahosted.freeotp.MainActivity$3.doInBackground(MainActivity.java:324)
04-22 16:51:54.917 11973 12304 E AndroidRuntime:     at org.fedorahosted.freeotp.MainActivity$3.doInBackground(MainActivity.java:310)
04-22 16:51:54.917 11973 12304 E AndroidRuntime:     at android.os.AsyncTask$2.call(AsyncTask.java:304)
04-22 16:51:54.917 11973 12304 E AndroidRuntime:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
04-22 16:51:54.917 11973 12304 E AndroidRuntime:     ... 4 more
04-22 16:51:54.917 11973 12304 E AndroidRuntime: Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
04-22 16:51:54.917 11973 12304 E AndroidRuntime:     at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:385)
04-22 16:51:54.917 11973 12304 E AndroidRuntime:     at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:213)
04-22 16:51:54.917 11973 12304 E AndroidRuntime:     ... 13 more`

**Comment by helloworld1** [comment]
Are you trying to import the .json file exported by FreeOTP+? If not the app may crash. I will need to update to handle the error more gracefully if you are trying to import file with incorrect format
