### ISSUE TITLE
Button to generate a private key

### ISSUE THREAD

**Issue by OmlineEditor** [helloworld1/FreeOTPPlus#133]
I ask you to add a button to generate a private key. I need to enter it manually when creating a new private key, this is not convenient. make an automatic generation of a long private key secret.

**Comment by Minoru** [comment]
Hi! A fellow user here. What do you mean by "private key"? Do you mean the "Secret" field in the "Add Token" dialog? If so, that can't be generated in FreeOTP+. That secret is generated by the service whose token you're adding. The only way to avoid typing it is to scan the QR code using the camera.

**Comment by OmlineEditor** [comment]
ok thanks for the clarification
