### ISSUE TITLE
Another password to enter the application

### ISSUE THREAD

**Issue by OmlineEditor** [helloworld1/FreeOTPPlus#139]
There is very weak protection in the application now. The same password is used for entering the application as for unlocking the phone. If there is a simple graphic design for the phone then the same graphic design for the application is used. This is a very weak defense.
I ask you to create an individual password to enter the application. I also ask you to turn in the ability to encrypt the database with this password. analogue of this function what I want in KeePassDX application:
https://f-droid.org/ru/packages/com.kunzisoft.keepass.libre/

**Comment by helloworld1** [comment]
Eventually, I would like to use a user password to encrypt all the token secrets. The password will be required to open the app and decrypt the data. The password can also be encrypted in device secret storage protected by biometric. 
It requires quite some work to get this done though.

**Comment by helloworld1** [comment]
Let's consolidate the discussion in #128
