### ISSUE TITLE
Adding Hebrew - crowdin

### ISSUE THREAD

**Issue by tzagim** [helloworld1/FreeOTPPlus#142]
TNX

**Comment by 6543** [comment]
@tzagim happy translatung - may wana close this issue ;)

**Comment by tzagim** [comment]
@6543 And finish....

**Comment by tzagim** [comment]
@helloworld1
please pay attention
Google decided to use in Android IW code for Hebrew and not HE code.

**Comment by helloworld1** [comment]
That's very weird. I can move the files to values-iw or keep both iw and he.
I will use emulator to test the locale later.

**Comment by 6543** [comment]
this is strange ... will have to change config in crowdin so export will follow new name ... waiting for your test result :)

**Comment by helloworld1** [comment]
That's indeed very weird. I set the emulator locale to Hebrew and locale he-IL. It still displays English on emulator.

  $ adb shell getprop | grep locale
  [persist.sys.locale]: [he-IL]

 I moved `values-he` to  `values-iw` and it displays Hebrew correctly.

**Comment by tzagim** [comment]
It is also possible to make a shortcut from values-he to values-iw.

**Comment by helloworld1** [comment]
Google has a lint check and ask devs to use values-iw insteads of he. It gives the reason there:
https://android.googlesource.com/platform/tools/base/+/master/lint/libs/lint-checks/src/main/java/com/android/tools/lint/checks/LocaleFolderDetector.java#67

So I think we are good on just moving values-he to values-iw

**Comment by helloworld1** [comment]
@6543 Would you help to move Crowdin translations to values-iw? I can merge a PR later. Thanks!

**Comment by 6543** [comment]
Yes sure just give me some time :)

**Comment by tzagim** [comment]
> 
> 
> @6543 Would you help to move Crowdin translations to values-iw? I can merge a PR later. Thanks!
#155

**Comment by 6543** [comment]
I could not find the option to rename leter - I would have to add a "custom" language and call it Hebrew
