### ISSUE TITLE
edit provider - Cancel button display

### ISSUE THREAD

**Issue by rafalkrupinski** [helloworld1/FreeOTPPlus#144]
Using the latest version from f-droid

On the edit provider screen, Cancel button text is misaligned

![signal-2021-08-15-163009](https://user-images.githubusercontent.com/3732079/129481905-151c4882-6a20-42f5-824d-d92bb5657bb6.jpeg)

**Comment by helloworld1** [comment]
Emmm, I am not able to reproduce. But what is your system locale?

**Comment by rafalkrupinski** [comment]
I was on English (XC), changed to different English and it's alright

**Comment by helloworld1** [comment]
Fixed in https://github.com/helloworld1/FreeOTPPlus/commit/a8acf59fe8e99f6ed5918963eac7df603099a3c8
