### ISSUE TITLE
[Feature request] Follow system settings regarding dark theme

### ISSUE THREAD

**Issue by Kernald** [helloworld1/FreeOTPPlus#145]
Recent versions of Android (a few years) support automatically switching from a dark to a light theme depending on the time of the day (e.g. dark at night, light in the day). This makes apps like FreeOTP+ annoying to use, because while they support a dark theme, they're in the wrong state ~half of the time.

The current implementation seems to be following the battery saver setting only (unless the dark mode is explicitly enabled):

https://github.com/helloworld1/FreeOTPPlus/blob/f1f5a43dca9a78995882029965ac10884ed7915e/app/src/main/java/org/fedorahosted/freeotp/FreeOtpPlusApplication.kt#L13-L20

Using [`MODE_NIGHT_FOLLOW_SYSTEM`](https://developer.android.com/reference/androidx/appcompat/app/AppCompatDelegate#MODE_NIGHT_FOLLOW_SYSTEM) instead would be more in line with user's expectations, I think.

**Comment by helloworld1** [comment]
That's a good suggestion. Thanks.

**Comment by helloworld1** [comment]
I have changed to follow system theme https://github.com/helloworld1/FreeOTPPlus/commit/f04a154640789918c2975b30f7351e81a67c540e
