### ISSUE TITLE
The statusbar remains blue in dark mode

### ISSUE THREAD

**Issue by Kernald** [helloworld1/FreeOTPPlus#146]
In dark mode, the status bar (top of the screen) remains a bright and vivid blue, while other apps usually opt for a much less distracting neutral dark grey or black - maybe the same as the toolbar.

**Comment by helloworld1** [comment]
Thanks for reporting. This is definitely a bug in the theming and will fix.

**Comment by helloworld1** [comment]
The issue is now fixed in https://github.com/helloworld1/FreeOTPPlus/commit/5f93d0341ef224c90a1201c23c52095d9a5efb29

**Comment by helloworld1** [comment]
![Screenshot_20220312_221123](https://user-images.githubusercontent.com/247316/158047466-c3e01a25-d508-470d-b4bb-6ac51277c97f.png)
