### ISSUE TITLE
Breaking auto update on F-Droid

### ISSUE THREAD

**Issue by jugendhacker** [helloworld1/FreeOTPPlus#148]
Looks like https://github.com/helloworld1/FreeOTPPlus/commit/0bf0ff3e0dad249c5aef1a6fe0a92ae1efbb228b broke auto update for F-Droid, because it can't get the version name and code directly from the build.gradle of the app. I'll submit the 2.4 manually to F-Droid, but it would be nice if we could find a solution for it, maybe together with F-Droid team.

**Comment by helloworld1** [comment]
Thank you for helping investigating the issue. Let me revert back the version code handling to build.gradle.kts for now since new AGP do not seem to need library project to be versioned anymore.

**Comment by jugendhacker** [comment]
That would be the easiest option of course.

**Comment by jugendhacker** [comment]
Okay so the F-Droid team came up with a solution, that nothing needs to be changed on your side. Sorry for interrupting.

**Comment by helloworld1** [comment]
That's great! Thanks!
