### ISSUE TITLE
Scan QR code quits without adding the scan to list of accounts

### ISSUE THREAD

**Issue by Aeny202** [helloworld1/FreeOTPPlus#15]
I have this happening with the several slack accounts (different teams) where I use the same email address. It seems that if the email address is not the same then you can add multiples with the QR scanner. 

Steps to reproduce: 
1. Join a slack team with an email address
2. Turn on 2FA for that account and scan the QR code, enter the given code into slack and finish the 2FA process
3. Join another slack team with the same email address
4. Turn on 2FA for that account and scan the QR code

Result: 
1. Scanner will close without adding the account

Expected result: 
1. Possibility to add multiple slack accounts

Workaround:
1. Manually enter the time-based key in FreeOTP+ generated by slack when clicking the can't scan this barcode link

Version and device:
1. Sony Z5 Compact running Android 7.1.1 with FreeOTP+ version 1.0 from the FDROID store

EDIT: If there's any logs I can provide then please let me know which ones you'd like to see.

**Comment by wesinator** [comment]
https://github.com/freeotp/freeotp-android/issues/67

**Comment by helloworld1** [comment]
I wonder what is different between account. Are the issuer and account exactly the same for two account?  In the latest version of FreeOTP+, as long as one is different, they will be  treated as different token

**Comment by ndorf** [comment]
@helloworld1 Yes, I think the issuer and account are the same, hence the problem. In the case of Kraken, tokens do in fact correspond to the same account, but they control access to different actions (for instance, one to log in, another to trade, and yet another to withdraw funds).

Even if this is invalid, some kind of error message should be displayed. Otherwise it's not obvious that the new token was ignored; an inattentive user might assume that the new one overwrote the old one.

Better IMHO would be to allow the user to choose to "Overwrite, Rename or Cancel."

**Comment by helloworld1** [comment]
Thanks @ndorf for providing details. Yea, same issuer and account is the problem here. Maybe I can add some conflict detection and rename the issuers with a suffix like "-1" "-2".. etc.

**Comment by AGlezB** [comment]
Same here. It said "Token added" but did nothing. I had to manually input the secret.
As for conflic detection you can use the secret. Same issuer and account but different secret ask to override existing o create new.

**Comment by bodograumann** [comment]
The same problem occurs if you want to reset the otp credentials.
You would scan a qrcode with the same descriptors, but a new key, that should replace the existing key.
The app says it scanned successfully, but simply discards the new key.

**Comment by helloworld1** [comment]
The recent DB changes has changed the behavior. If you scan a code, a new token is always created regardless if it exists or not. You can delete the old one if you don't want duplicated code.
