### ISSUE TITLE
Option to setup columns number

### ISSUE THREAD

**Issue by masscream** [helloworld1/FreeOTPPlus#150]
Since last update, the providers list has been split into two columns. That is not generally a bad idea, but it needs a little improvement. Otherwise on the phones like my Pixel, I can see only 5 digits of any code it provides until I rotate it on the widescreen format, which is not very convenient. Please add the option to manage columns number or implement #136. Thank you

**Comment by drtheuns** [comment]
I just updated the app and it went from list view to grid view. As a result I can only see 4 OTP digits per provider, meaning I can no longer effectively use the app (except for relying on the copy-to-clipboard). Please allow for some way to customize this.

**Comment by helloworld1** [comment]
There is a miscalculation in the column calculation. This is fixed in https://github.com/helloworld1/FreeOTPPlus/commit/59c124fe1ca7cdfbed36bbc1661c6a70b9c851bb

**Comment by helloworld1** [comment]
2.5 was released to fix the issue.
