### ISSUE TITLE
Code no longer readable since UI upgrade

### ISSUE THREAD

**Issue by jan0sch** [helloworld1/FreeOTPPlus#152]
Hi,

since the latest upgrade (including UI improvements for tablets) I can no longer view the codes on my phone because they are displayed into two columns and each column only displays half of the code. So I have to copy the code to the clipboard and paste it into some other app (editor), read it from there, type it into the 2FA screen on the device (usually a computer) where I need it and finally delete it again on the phone (clear clipboard, close "helper" app).

I searched for an option to disable this but found nothing. Is there a way to get the old UI back or at least disable the columns?

Version: FreeOTP+ 2.4 (15) via F-Droid

Kind regards,

**Comment by jugendhacker** [comment]
Duplicate of #151 and already fixed in version 2.5, we just need to wait a bit for F-Droid to build and deploy.

**Comment by jan0sch** [comment]
Nice! Thank you very much. :heart:
