### ISSUE TITLE
import from json ignores entries with empty issuerExt

### ISSUE THREAD

**Issue by jkarlson** [helloworld1/FreeOTPPlus#153]
While it may be incorrect, QR import accepts entry with exported JSON like:
```
    {
      "algo": "SHA1",
      "counter": 0,
      "digits": 6,
      "issuerExt": "",
      "label": "{token.label}",
      "period": 30,
      "secret": [
```
however import does not import it back

**Comment by helloworld1** [comment]
Will investigate

**Comment by helloworld1** [comment]
I can actually import correctly for the following token with issuerExt as empty and a valid label. Is there anything that I am missing?

`{
    "tokenOrder": [
        "aaa"
    ],
    "tokens": [
        {
            "algo": "SHA256",
            "counter": 1,
            "digits": 6,
            "image": "https://osu-wams-blogs-uploads.s3.amazonaws.com/blogs.dir/4169/files/2021/01/google_2015_logo.png",
            "issuerExt": "",
            "label": "aaa",
            "period": 30,
            "secret": [
                113,
                70,
                41,
                20,
                -69,
                -12,
                -71,
                58,
                -58,
                -30,
                41,
                105,
                100,
                -72,
                28,
                25,
                -62,
                -62,
                -15,
                50,
                -34,
                -4,
                -81,
                10,
                51,
                85,
                -68,
                108,
                67,
                -77,
                75,
                33,
                -31,
                66,
                -117
            ],
            "type": "HOTP"
        }
    ]
}`

**Comment by jkarlson** [comment]
maybe issue is `"{token.label}"`, which did probably get replaced with corresponding entry from tokenOrder or something that export just omitted and I don't have access to anymore. For me tokenOrder contained `:reasonableLabel`, so as I read this as a human no data is missing.

**Comment by jkarlson** [comment]
this does not import for me
```
{
"tokenOrder": [
    "aaa"
],
"tokens": [
    {
        "algo": "SHA256",
        "counter": 1,
        "digits": 6,
        "issuerExt": "",
        "label": "{token.label}",
        "period": 30,
        "secret": [
            113,
            70,
            41,
            20,
            -69,
            -12,
            -71,
            58,
            -58,
            -30,
            41,
            105,
            100,
            -72,
            28,
            25,
            -62,
            -62,
            -15,
            50,
            -34,
            -4,
            -81,
            10,
            51,
            85,
            -68,
            108,
            67,
            -77,
            75,
            33,
            -31,
            66,
            -117
        ],
        "type": "HOTP"
    }
]
} 
```

**Comment by helloworld1** [comment]
Alright, found the issue. A token template replacement was incorrectly done. Fixed in https://github.com/helloworld1/FreeOTPPlus/commit/f2dc184000bfc226367d44894a24c9d16ed5fc95

**Comment by jkarlson** [comment]
thanks, so I interpret it was just export after all?
