### ISSUE TITLE
Clicking the button to generate a new code still shows the old code

### ISSUE THREAD

**Issue by tomasradej** [helloworld1/FreeOTPPlus#156]
After the update, clicking the button to generate a new code shows the old code indefinitely.

Steps to reproduce:

1. Click the button to generate a code
2. Wait for the code to expire
3. Click the button again to generate a new code

Expected results: a new code is shown. (Was the case before update)

Actual result: the old code is shown.

The issue can be worked around by changing the orientation of the screen and clicking the button again.

EDIT: reformatted to read like a proper bug report.

**Comment by helloworld1** [comment]
I do find a weird issue. This seems to only apply to certain tokens. Some tokens are working correctly.

**Comment by helloworld1** [comment]
Does it only happen to HOTP token or happens also in TOTP tokens?

**Comment by tomasradej** [comment]
I only have one HOTP token.

**Comment by helloworld1** [comment]
Confirmed the issue on HOTP. Will fix the issue

**Comment by tomasradej** [comment]
Thanks!

**Comment by helloworld1** [comment]
The issue should be fixed in this https://github.com/helloworld1/FreeOTPPlus/commit/3b40b9bff910a4b8b3e5ab6cc2d9b8a0149f0443

Are you willing to beta testing it? 
You can download this debug version
https://drive.google.com/file/d/1nvVGTeArC_5FPXIL86yexzJIJxee3uFU/view?usp=sharing
It can co-exist with the release with and it has an orange icon.

**Comment by tomasradej** [comment]
Thanks! Sure, I'll test it, but I can't test it with the very code I'm having the issue with (I'll need to provision a new one).

**Comment by helloworld1** [comment]
Personally I don't have any HOTP to test. Would be glad to hear any feedbacks. I will add automated testing in the future.

**Comment by tomasradej** [comment]
I have tested the debug version from GDrive with a new HOTP token, and it works as expected. Thanks a lot!
