### ISSUE TITLE
Release 2.5 version in Google Playstore

### ISSUE THREAD

**Issue by whoami213** [helloworld1/FreeOTPPlus#158]
Hi Please release version 2.5 in Google Playstore for Android, the version in there is still 2.3

**Comment by helloworld1** [comment]
Due to major internal changes, there are some bug needs to be sorted out first. Probably next version will be available on Google Play Store.
The APK released here is signed with the same key as Google Play release so you can just install over your current Google Play installs.

**Comment by lemmy04** [comment]
I switched to the apk from f-droid, that one is version 2.5.

**Comment by helloworld1** [comment]
Version 2.7 is released to the Google Play Store.
