### ISSUE TITLE
Imported backup disappear after app closes

### ISSUE THREAD

**Issue by andreapx** [helloworld1/FreeOTPPlus#16]
I've imported a previously exported backup, but when I exit and enter the app again, it's empty.
I've tried importing, exporting with the actual app and then reimporting, but without success.
Version 1.0 installed with F-Droid

**Comment by helloworld1** [comment]
Would you try the latest version 1.3 and let me know if it still happens? I cannot reproduce the issue myself.

**Comment by helloworld1** [comment]
Closing this issue now. Please re-open if you can give more detailed repo steps.
