### ISSUE TITLE
UI on smartphone is difficult to use

### ISSUE THREAD

**Issue by Mte90** [helloworld1/FreeOTPPlus#160]
With the latest releases now I have the list of the services in 2 columns in my smartphone.
If I tapped to a service, the number is showed but is cut because of the 2 columns.
So I rotate, the number is hidden again and I have to tap to see it.
Maybe the size of my smartphone is big enough for 2 columns but not so much?

It is a OnePlus 5G and I cannot do a screenshot as is not allowed from the app.

**Comment by helloworld1** [comment]
Which version are you using? The latest version 2.5 should have fixed the issue. Please update and report back. Thanks!

**Comment by Mte90** [comment]
Yes you are right the latest version fixed it!
Thanks!

**Comment by helloworld1** [comment]
Thanks for reporting back!
