### ISSUE TITLE
App crash when using search function

### ISSUE THREAD

**Issue by Ascendor** [helloworld1/FreeOTPPlus#165]
Hey, since version 2.6 the app crashes when using the search function and then revealing a code in the result list. 

When revealing the same code in the full list, the app does not crash.

Restarting the app and deleting cache did not help.

**Comment by helloworld1** [comment]
Thanks for reporting the bug. I am able to reproduce and will fix in the next release

**Comment by helloworld1** [comment]
Fixed in https://github.com/helloworld1/FreeOTPPlus/commit/7b48de539c526744c44efc3b7940e7612fc07be2

**Comment by helloworld1** [comment]
I added integration test to prevent this from happening
https://github.com/helloworld1/FreeOTPPlus/commit/e0fe9850ba028af484723e66756f550b26149568

**Comment by vbrandl** [comment]
I just stumbled across the same issue. Do you plan to publish a release to fix this?

**Comment by helloworld1** [comment]
Will release soon after all the translation updates are in
