### ISSUE TITLE
Copycat on Google Play

### ISSUE THREAD

**Issue by Poussinou** [helloworld1/FreeOTPPlus#17]
Hi @helloworld1 

I found [this app](https://play.google.com/store/apps/details?id=com.batgioi.freeotpplus) on the Google Play Store. This guy just took your source code, added some ads in it and put it on the Store, without warning this is free software...

As you are the owner of the source code, feel free to open a request to google [here](https://support.google.com/legal/contact/lr_dmca?product=googleplay) to remove this copy from the Store, if it's your wish ;)

Don't forget to tell Google that:

* The app is licensed under Apache v2 license and this guy is violating it;
* He is falsely claiming he made the app;
* Provide some screenshots of your own app.

**Comment by helloworld1** [comment]
Thanks a lot for flagging this app. I have opened a request to Google to remove the app. Waiting for response now.

**Comment by Poussinou** [comment]
Thanks 👍 
Do not hesitate to copy past the links of new copycats in the future so I can track them :)
