### ISSUE TITLE
How do i recover my auth password ?

### ISSUE THREAD

**Issue by Hitoshifw0x2** [helloworld1/FreeOTPPlus#171]
My OTP code is locked on app because i forgot the Personal Authentication Password, so i cant do anything is there any recovery things for the app ? If yes i need it as soon as possible.
Thanks

**Comment by helloworld1** [comment]
I don't know any good ways. If you can use adb command line, you can try to do an adb backup on the package name "org.liberty.android.freeotpplus".  Then you can restore after you did a factory reset. You can restore the backup after reset the password.

Here are some guide for bakcup
https://android.stackexchange.com/questions/182381/is-it-possible-to-backup-and-restore-an-app-with-data-via-adb

**Comment by Hitoshifw0x2** [comment]
Hey can i req something ?

**Comment by Hitoshifw0x2** [comment]
Mmmmm can you add some like api token thing (api login token) or like you need session or login to your app for access the otp app like session ID things ummmmm i think its gonna be good mmmmm... I dunno if you want to apply it i think its gonna be great. just idea Thanks
