### ISSUE TITLE
Scanning QR code difficulty due to lack of focussing

### ISSUE THREAD

**Issue by Rikitik** [helloworld1/FreeOTPPlus#173]
I'm trying to switch from FreeOTP to FreeOTP+, because the import/export function.
Unfortunatly just like issue #61 i can't scan the QR code at ALL(blurry image)
 tryng it on FreeOTP works n one go :(

LineageOs 18.1

**Comment by helloworld1** [comment]
Are you using version 2.7? I think the new Google said CameraX is compatible with about 90% of the phone at the market. What is your phone model?

**Comment by helloworld1** [comment]
I bumped the camerax version again in https://github.com/helloworld1/FreeOTPPlus/commit/06317d2343d16132a5a559bed837c76f1e2a4a7e
Hopefully it will help with focusing compatibility
