### ISSUE TITLE
Overflow menu is not easily visible on EMUI on dark theme

### ISSUE THREAD

**Issue by AGlezB** [helloworld1/FreeOTPPlus#175]
Please add some way to delete entries.
Not being able to delete is more of a bug than a missing feature.

**Comment by helloworld1** [comment]
You can delete an entry by clicking in the "..." overflow menu on the right of each entry and select "delete". Let me know if it works.

**Comment by AGlezB** [comment]
Ahhh. I see. This is a different issue then.
In my Xiaomi 11 with MIUI 12.5.9 the overflow is not visible in dark mode.
Unchecking `Use dark theme` in the menu makes it barely vissible.
I tried taking a screenshot but the app doesn't allow it.

**Comment by helloworld1** [comment]
Hmmmm, I think it is EMUI specific issue. And yea, I disabled screenshot as a feature request for security reason. Will try to modify and see if the contrast improves on EMUI.

**Comment by AGlezB** [comment]
> Hmmmm, I think it is EMUI specific issue. And yea, I disabled screenshot as a feature request for security reason. Will try to modify and see if the contrast improves on EMUI.

Thanks a lot!

**Comment by helloworld1** [comment]
I made the overflow menu to be brighter in this commit https://github.com/helloworld1/FreeOTPPlus/commit/4d2c87607fc870c39c85fdab2bec284b41c2ac36
Hopefully it will fix the issue

**Comment by AGlezB** [comment]
> I made the overflow menu to be brighter in this commit [4d2c876](https://github.com/helloworld1/FreeOTPPlus/commit/4d2c87607fc870c39c85fdab2bec284b41c2ac36) Hopefully it will fix the issue

Awsome! Thanks a lot!
