### ISSUE TITLE
App crashes on Android 8.1 on IMPORT

### ISSUE THREAD

**Issue by itsKV** [helloworld1/FreeOTPPlus#18]
App is crashing while importing .db file on Android 8.1
This happens every time importing using any file explorer (stock/third party) or any file hosting service app (GDrive, dropbox etc)
Kindly fix the issue.

**Comment by helloworld1** [comment]
You should import the json file exported from FreeOTPPlus, not other files. Could you confirm the file type you are trying to import?

**Comment by itsKV** [comment]
yes, solved the problem. My file manager is giving me .db file as backup (idk why). Tried via Telegram. Succeeded with .json
