### ISSUE TITLE
[Language Specific] Button "Delete" looks weird for Russian

### ISSUE THREAD

**Issue by Nickoriginal** [helloworld1/FreeOTPPlus#180]
<details><summary>Original image</summary><img src="https://user-images.githubusercontent.com/85299944/149340749-ee8f9f8b-27e3-4c40-991a-9afc0848c730.jpg"></details>
Captured by another camera, because screenshots are not possible.

To reproduce:
1. Change your system locale to Russian.
2. Create any token (you can also take exist) and try to delete it.
3. Look at the "Delete" button (Удалить). It is a little bit shifted down and text is truncated.

Samsung Galaxy A20s, Android 11, build A207FXXU2CUI2

**Comment by helloworld1** [comment]
Will take a look the issue. The same can cause truncated delete button on a narrow phone.

**Comment by helloworld1** [comment]
The issue should be fixed in https://github.com/helloworld1/FreeOTPPlus/commit/a8acf59fe8e99f6ed5918963eac7df603099a3c8
I tested Russian language and works fine now
