### ISSUE TITLE
[Feature Request] Add Checkbox to Allow Screenshots

### ISSUE THREAD

**Issue by KimBrodowski** [helloworld1/FreeOTPPlus#184]
For security reasons, FreeOTP+ blocks screenshots. This make some amount of sense, since screenshots can be abused by malicious software.

However, this also makes writing instructions for others unnecessarily difficult.

I've encountered this issue twice now. Once when I was writing instructions on how to set up TOTP for non-tech-savvy users. Together with missing iOS support this the reason why we didn't end up with FreeOTP+ as our primary recommendation. There are ways to get screenshots anyway, but it makes the process harder.

The 2nd time I ran into this is when deciding upon the format of our otpauth URIs. Unfortunately it seems like parsing there is a bit of mess. I'd consider FreeOTP+'s parsing and display logic to do what I expected, however this is not true for other implementations. Sharing our observations was made more difficult by preventing screenshots.

For these reasons, I'd suggest adding a checkbox to temporarily allow screenshots.

**Comment by helloworld1** [comment]
The feature is implemented through an app shortcut. Long click on the app icon and launch with "Screenshot mode" shortcut. The app will be launched with screenshot enabled

https://github.com/helloworld1/FreeOTPPlus/commit/1da4527deca77ba1be603f8ad738c892ce848232

**Comment by helloworld1** [comment]
The feature is implemented through an app shortcut. Long click on the app icon and launch with "Screenshot mode" shortcut. The app will be launched with screenshot enabled

https://github.com/helloworld1/FreeOTPPlus/commit/1da4527deca77ba1be603f8ad738c892ce848232

**Comment by helloworld1** [comment]
![s](https://user-images.githubusercontent.com/247316/158046727-9ba659b1-61cd-473e-8187-aca3c206ec1d.jpg)
