### ISSUE TITLE
Please enable the "GitHub Discussions" feature

### ISSUE THREAD

**Issue by unforgettableid** [helloworld1/FreeOTPPlus#187]
Dear @helloworld1:

There is no FreeOTP+ email list. Can you please enable the "GitHub Discussions" feature instead?

It is quite easy to do.

If you want to enable the feature, you simply do this:

* Go to https://github.com/helloworld1/FreeOTPPlus/settings.
* Scroll down.
* Click the green "Set up discussions" button.
* Scroll down again.
* Click the green "Start discussion" button.

What do you think?

Thank you for reading this!

**Comment by helloworld1** [comment]
Done. Thanks for the suggestion
