### ISSUE TITLE
Update on F-Droid

### ISSUE THREAD

**Issue by JakubMajcher** [helloworld1/FreeOTPPlus#19]
On Google Play there is 1.2 version, on F-Droid 1.0. Will You update app on F-Droid?

**Comment by Rudloff** [comment]
Hello,

We are going to update the app in F-Droid (see https://gitlab.com/fdroid/fdroiddata/merge_requests/4269), but would it be possible to use [Git tags](https://github.com/helloworld1/FreeOTPPlus/tags) so we can easily know when a new stable release is published?

**Comment by helloworld1** [comment]
I will make sure the 1.3 version will be tagged for release
