### ISSUE TITLE
Twitter codes stopped working

### ISSUE THREAD

**Issue by sid-the-sloth** [helloworld1/FreeOTPPlus#190]
I got FreeOTPPlus working with many sites, including github, gitlab, twitter, etc.
Yesterday I logged on to Twitter in the browser, got the prompt to enter the verification code from FreeOTPPlus.

Twitter says the code is not good, no matter how many times I try.

In the end I had to use a backup code.

Disabled and re-enabled the 2FA on Twitter, re-created the entry in FreeOTPPlus several times, but no luck no matter what.

Can somebody re-produce this, please?

EDIT: nevermind, I also used Google Authenticator, same problem...

**Comment by sid-the-sloth** [comment]
Nothing, anybody?

**Comment by helloworld1** [comment]
Let me enable 2FA on twitter and test

**Comment by helloworld1** [comment]
I have tried 2FA log in using FreeOTP+ on multiple devices and all of them are working correctly.
I also cross checked google authenticator and compare the code between FreeOTP+  and Authenticator. They showed the same code.
