### ISSUE TITLE
Release-version in Play Store?

### ISSUE THREAD

**Issue by Juarrow** [helloworld1/FreeOTPPlus#191]
[Here](https://github.com/helloworld1/FreeOTPPlus/issues/158#issuecomment-988501521) is stated that 2.7 is released to the Play Store.

But 
![image](https://user-images.githubusercontent.com/5290648/156990599-d058ccc9-3069-4b89-a75f-9542a647d8ed.png)

Did you forget to update the version number? (is it even possible to use a previous version number twice?)

**Comment by helloworld1** [comment]
I made a mistake when rolling out the version. Only 50% gets the latest version.
Now it is 100%. Thanks for notifying me the issue.
