### ISSUE TITLE
Share token via QR code [HELP WANTED]

### ISSUE THREAD

**Issue by Nickoriginal** [helloworld1/FreeOTPPlus#193]
Hello, I've copied and moved all @xiongzi's commits from his closed [PR](https://github.com/helloworld1/FreeOTPPlus/pull/186) in my repo, so you can now merge it. Unfortunately, I can not squash commits so there is 8 commits. Can you accept my pull? (with author's indication)

**Comment by Nickoriginal** [comment]
No, I just forked main repository and copied new files and code strings from PR to my fork. Cherry-picking, as well as squashing is available in the advanced tools, but I do not have access to them. I think that these changes are really useful for users. I want to pay some attention for this and finally implement this feature: no matter who will do this.

**Comment by jugendhacker** [comment]
What do you mean by advanced tools? cherry picking is a normal git feature and ensures proper attributions to the original author...

**Comment by helloworld1** [comment]
I do have some comments regarding the original PR. Mainly I don't quite like creating SquareRelativeLayout. If anyone can help addressing this, I can merge it soon. Otherwise, I will probably do it myself later.

**Comment by helloworld1** [comment]
I cherry picked https://github.com/helloworld1/FreeOTPPlus/commit/da7694dbe5bcd599e68b93cec107d3021de34ef6 and thoroughly refactored the UI and the code by this commit https://github.com/helloworld1/FreeOTPPlus/commit/ce908fb7e237a78afc685c973449060f6010c82a

Closing this issue.

**Comment by helloworld1** [comment]
I cherry picked https://github.com/helloworld1/FreeOTPPlus/commit/da7694dbe5bcd599e68b93cec107d3021de34ef6 and thoroughly refactored the UI and the code by this commit https://github.com/helloworld1/FreeOTPPlus/commit/ce908fb7e237a78afc685c973449060f6010c82a

Closing this issue.
