### ISSUE TITLE
Perfekt Tool, but looking for self hosted tool/script using FreeOTP+ export file

### ISSUE THREAD

**Issue by pm-pm** [helloworld1/FreeOTPPlus#194]
Hello,
many thanks for this great tool. No complains! :-)

I am looking for a self hosted tool/script (e.g. on linux server) where i can load into the export file from FreeOTP+ in and use this as an alternative when the smartphone is out of order.

Does anyone have information on this?

pm-pm

**Comment by helloworld1** [comment]
I used Keepass on Linux with this plugin https://github.com/KeeTrayTOTP/KeeTrayTOTP
It doesn't import the FreeOTP+ exports directly, but you can copy the secrets to it and use it on your PC.

**Comment by oyale** [comment]
Maybe @pm-pm could take a look on https://github.com/Bubka/2FAuth; it's a self-hosted web app. There's no direct importer (as far as I know), but you can use its [API](https://docs.2fauth.app/resources/rapidoc.html#post-/api/v1/twofaccounts) with a script to update it with FreeOTPPlus tokens.
