### ISSUE TITLE
Apply for the review for the Advanced Protection approval

### ISSUE THREAD

**Issue by omasanori** [helloworld1/FreeOTPPlus#195]
Reference: https://support.google.com/accounts/answer/9764949

**Comment by helloworld1** [comment]
Thank you for your suggestion. I have read the guideline but I don't think I can apply for it because of the limited installation criteria. I want the app to be also available in F-Droid. 

```
Limited installations outside the Play Store 

When you’re enrolled in Advanced Protection, harmful software sources are blocked for your Android devices. You can’t download new app installations from most sources outside the Play Store.
```

**Comment by omasanori** [comment]
I appreciate your consideration! However, that is a criterion for a user account, as far as I know. An Advanced Protection-enabled account can not install an app from third parties.

On the other hand, in Play Store, an Advanced Protection-enabled account sees an indicator if Google passes an app an additional security review, which I proposed.

**Comment by helloworld1** [comment]
Got it. I have applied the advanced protection for developer
```
Advanced Protection App Submission Form
Thank you for your submission to the Advanced Protection Program. 
```
