### ISSUE TITLE
RELEASE-2.8

### ISSUE THREAD

**Issue by 6543** [helloworld1/FreeOTPPlus#197]
@helloworld1 I would merge #196 and wait for ~few days to get translations ...

and then tag `RELEASE-2.8` so fdroid will pick up the new release :)

**Comment by helloworld1** [comment]
Yea, sound good. I merged the PR and will wait for translations to be merged to release 2.8. I have been testing 2.8 for a while without major issues.

**Comment by 6543** [comment]
@helloworld1 ->  #199

**Comment by helloworld1** [comment]
All translation complete and ready for release?

**Comment by 6543** [comment]
@helloworld1 no and it looks like there wont more atm

**Comment by 6543** [comment]
@helloworld1 we got one more: #201

**Comment by helloworld1** [comment]
With all merged. 2.8 is now released.
