### ISSUE TITLE
 Current version not available in F-Droid Store

### ISSUE THREAD

**Issue by Krawei** [helloworld1/FreeOTPPlus#20]
Dear team,

when I take a look in the play store the current version is 1.2, in the F-Droid store the current version is 1.0. What's the reason for this gap? Is there a bug in the build process?

Please fix this.

Kind Regards,

Krawei

**Comment by Krawei** [comment]
Any updates here?

**Comment by jugendhacker** [comment]
Duplicated with #19

**Comment by helloworld1** [comment]
I will make sure 1.3 version will be tagged for release. I wonder if F-Droid will pick up automatically.

**Comment by helloworld1** [comment]
The version 1.3 is released and tagged with RELEASE-1.3.

**Comment by jugendhacker** [comment]
If you keep the tagging scheme automatic "pick ups" could be configured

**Comment by helloworld1** [comment]
Good to know. Thanks! I am not sure how to update the F-Droid metadata to do that. Is there anyone who can help?

**Comment by jugendhacker** [comment]
I already created a merge request... see https://gitlab.com/fdroid/fdroiddata/merge_requests/4871/

**Comment by helloworld1** [comment]
Nice Thanks @jugendhacker.

**Comment by wjoe** [comment]
Seems that 1.2 is on F-Droid but not 1.3

**Comment by jugendhacker** [comment]
@wjoe it will in a few days... the signing process takes some time...

**Comment by jugendhacker** [comment]
It is there now so I think this issue could be closed...

Btw fdroid will now automatically build new versions when they get tagged

**Comment by helloworld1** [comment]
Great! Thanks a lot @jugendhacker, Version 1.4 will be released soon with search an other improvement so we will test the auto build there.

**Comment by helloworld1** [comment]
@jugendhacker It has been one more week. The app is still not on F-Droid. Is there a build failure or anything I need to address?

**Comment by jugendhacker** [comment]
@helloworld1 you now use .kts file for compiling and the fdroid autoupdate check has a know bug so it does not register/detect a new version... for now I'll add every version manually again until the bug is fixed. So you don't have to change something!

**Comment by helloworld1** [comment]
Interesting, good to know. Thanks @jugendhacker !
