### ISSUE TITLE
[Feature request] Add Date and Time stamp to export file name

### ISSUE THREAD

**Issue by pm-pm** [helloworld1/FreeOTPPlus#200]
Hello.

It would be very useful to have a date and time stamp in filename. :-)

Now "freeotp_backup.txt", but this would be nice "freeotp_backup_20220428_0150.txt"
(Date in reverse Order for sorting in Filesystem)

.
Belonging to my [other feature request](https://github.com/helloworld1/FreeOTPPlus/issues/198) for exporting only selected token, the amount of exported token could be part of filename? I am unsure. Maybe some comments? :-)

freeotp_backup_20220428_0150_(22).txt
freeotp_backup_20220428_0150_(07).txt # Export of 7 token at 01:50h at 28.4.2022
freeotp_backup_20220428_0150_(all).txt # All? Or better the amount of exported token? ;-)

Thanks
pm-pm

**Comment by helloworld1** [comment]
That's a great idea. I like it.
