### ISSUE TITLE
[Bug] Import does *not* overwrite all existing tokens

### ISSUE THREAD

**Issue by lemmy04** [helloworld1/FreeOTPPlus#207]
I just imported a backup from my tablet onto my phone, and contrary to the warning it did **not** overwrite the existing tokens - it added the new ones at the end of the list, creating loads of duplicates, possible bad ones too if the token had been recreated since the last import.

**Comment by lemmy04** [comment]
I tried with both, both appended instead of overwriting.Von meinem/meiner Galaxy gesendet
-------- Ursprüngliche Nachricht --------Von: Howard Liberty ***@***.***> Datum: 14.06.22  22:10  (GMT+01:00) An: helloworld1/FreeOTPPlus ***@***.***> Cc: Mathias Homann ***@***.***>, Author ***@***.***> Betreff: Re: [helloworld1/FreeOTPPlus] [Bug] Import does *not* overwrite all existing tokens (Issue #207) 
Which format of backup are you using? I think the Json format should overwrite but not other formats.

**Comment by helloworld1** [comment]
Got it. This sounds like a behavior change by a change that allows the account with same issuer / account combo to be added. See https://github.com/helloworld1/FreeOTPPlus/issues/15

**Comment by helloworld1** [comment]
Yea, I think that's a reasonable way to deduplicate the token.

**Comment by lemmy04** [comment]
here's a fun bit: this weekend I tried again to copy my freeotp+ tokens from one device to the other, so i exported as json and imported on the other device, and this time around it **did** overwrite the existing tokens just fine o.0

**Comment by PhilKes** [comment]
@lemmy04 Thats probably due to the fact that when importing, the `id` (primary-key) is set to the index of the token in the JSON Token list. Therefore if you import a JSON once and then again, the second time all the same tokens will also have the same `id` and therefore will be correctly overwritten.
