### ISSUE TITLE
Feature request: Store keys in folders

### ISSUE THREAD

**Issue by spiffzilla** [helloworld1/FreeOTPPlus#21]
When having 20+ logins stored in app it's cumbersome to locate correct login.

A folder structure that let users categorise login based on service type would really make life easier

**Comment by helloworld1** [comment]
Does a searching function helping?

**Comment by andreapx** [comment]
I think that a folder structure could be quicker

**Comment by jalcine** [comment]
Searching would be faster; it's a constant time lookup versus folders that require you to know exact positioning.

**Comment by helloworld1** [comment]
Yea, I won't support folder. I may implement search in the future as https://github.com/helloworld1/FreeOTPPlus/issues/12
