### ISSUE TITLE
Please add Chinese Traditional translations

### ISSUE THREAD

**Issue by s8321414** [helloworld1/FreeOTPPlus#211]
Please add Chinese Traditional translations on Crowdin, I can contribute to it :smiley:

**Comment by 6543** [comment]
https://crowdin.com/project/freeotpplus/zh-TW

**Comment by s8321414** [comment]
> https://crowdin.com/project/freeotpplus/zh-TW

Thank you!

**Comment by helloworld1** [comment]
@6543 I noticed an issue in the Chinese translation. Both zh-CN and zh-TW are mapped to "zh" directory. And the PR overwrote the zh-CN with zh-TW instead of creating two different translations zh-CN for simplified Chinese and zh-TW for traditional Chinese. Can we fix this? Thanks!
https://github.com/helloworld1/FreeOTPPlus/commit/893b9166195085253c2b7399e8d949c50759405a
https://crowdin.com/project/freeotpplus/zh-CN
https://crowdin.com/project/freeotpplus/zh-TW

**Comment by 6543** [comment]
well we either make one default "zh" or just migrate to use long names for all ...

**Comment by helloworld1** [comment]
@6543 Is it possible to have mix and match, or we have to use long name for all?

**Comment by helloworld1** [comment]
Version 3.0 is released. However, the zh_CN and zh_TW issue is not addressed in this release. Hopefully we can have a resolution in the next version.

**Comment by 6543** [comment]
well asap I have time I do have a look into it

My guess: we have to switch namin convention ... the question is if it will be supported out of the box

**Comment by helloworld1** [comment]
Thanks @6543 I can change all the locale manually to full local name. But it may break crowdin so I didn't do that.

**Comment by 6543** [comment]
#236

**Comment by 6543** [comment]
(I did not test if the android framework just pick that up or if it break things ... so that still has to be done)

**Comment by helloworld1** [comment]
Thanks a lot @6543. I will test out and let you know.

**Comment by helloworld1** [comment]
@6543

**Comment by helloworld1** [comment]
@6543 Unfortunately I reverted the PR https://github.com/helloworld1/FreeOTPPlus/pull/236. The locale resource name should be values-en-rUS or values-de-rDE. The PR is missing the "r" for the country name.

**Comment by 6543** [comment]
@helloworld1 are you sure! that's not spec compliant - what localization framework is used?

**Comment by helloworld1** [comment]
https://developer.android.com/guide/topics/resources/providing-resources#AlternativeResources
Quote:
The language is defined by a two-letter [ISO 639-1](http://www.loc.gov/standards/iso639-2/php/code_list.php) language code, optionally followed by a two letter [ISO 3166-1-alpha-2](https://www.iso.org/obp/ui/#iso:pub:PUB500001:en) region code (preceded by lowercase r).

**Comment by 6543** [comment]
well there are standarts ... and there is android :/

I'll have a look

**Comment by 6543** [comment]
next try: #238 :laughing:

**Comment by helloworld1** [comment]
This time, it works great! Thanks!
