### ISSUE TITLE
[Feature Request] Compatibility with Github's own 2FA

### ISSUE THREAD

**Issue by TUstudents** [helloworld1/FreeOTPPlus#216]
The github.com is using 2FA, but it is not compatible with FreeOTP+. The supported apps here are
[1Password](https://support.1password.com/one-time-passwords/)
[Authy](https://authy.com/guides/github/)
[LastPass Authenticator](https://lastpass.com/auth/)
[Microsoft Authenticator](https://www.microsoft.com/en-us/account/authenticator/)

The generated QR code is not recognized by FreeOTP.

Does somebody have the right parameters and could implement?

**Comment by pm-pm** [comment]
It works for me.
Check your app. You are using FreeOTP+, and not FreeOTP ?

**Comment by TUstudents** [comment]
It is FreeOTP+ 2.8 (org.liberty.android.freeotpplus) from Fdroid.
The QR code generated on
https://github.com/settings/two_factor_authentication/setup/intro
is not recognized, the circle in the lower right corner is spiraling to death.

**Comment by 6543** [comment]
Can you cros test with a other qrcode scaner what gets submited?

We might just bump a dep. if there is a new version for the qrcodes scan lib we use? Cc @helloworld1

**Comment by helloworld1** [comment]
GitHub works for me also. The qr library is already the latest compatible version. I wonder if it might be the camera compatibility issue. In the next version, I will bump the camerax dependency and see if it helps.

**Comment by helloworld1** [comment]
Originally the cameras-view dependency is using alpha version. Now I updated to the 1.1.0 release version. Probably it may resolve some issues.

**Comment by helloworld1** [comment]
I am closing the issues now. But feel free to reopen if you can actually get content of the QR code by using another scanner app to scan and copy out the actual content, and then mask out the sensitive secrets there, and paste here.

**Comment by 6543** [comment]
well just delete and let regenerate the totp and you can copy the whole thing ...

**Comment by TUstudents** [comment]
I changed the Github website theme manually from dark mode to white. Now the QR code is recognized correctly. So it is an issue with background interfering with QR code.
