### ISSUE TITLE
[Feature idea] Allow exporting individual tokens as `otpauth://` URI

### ISSUE THREAD

**Issue by webknjaz** [helloworld1/FreeOTPPlus#221]
It is now possible to copy an individual secret for each token but then, one would need to separately copy other params. It would be great to be able to copy a string encapsulating all of such details per https://github.com/google/google-authenticator/wiki/Key-Uri-Format. Tools like Bitwarden accept this format natively: https://bitwarden.com/help/authenticator-keys/#support-for-more-parameters.

**Comment by helloworld1** [comment]
I have added function to share token to Google authenticator or other apps https://github.com/helloworld1/FreeOTPPlus/commit/5b8e4eab57594f0a47837324592b6919a499af82
