### ISSUE TITLE
[Translation] Add catalan language

### ISSUE THREAD

**Issue by minterior** [helloworld1/FreeOTPPlus#224]
I can help with this. Is it just a matter of creating a PR that adds a new file under `/app/src/main/res/values-ca`?

**Comment by jugendhacker** [comment]
Actually translations are handled via [crowding](https://crowdin.com/project/freeotpplus) and @6543 just needs to enable Catalan there

**Comment by 6543** [comment]
done

**Comment by minterior** [comment]
Hi. I did my job and translated every string into Catalan in Crowdin: https://crowdin.com/project/freeotpplus/ca.

When could it be available in Google Play for the Android app? Thank you.

**Comment by helloworld1** [comment]
It is already merged. It will be available in the next release. Hopefully some time in December this year.

**Comment by minterior** [comment]
I can see [this PR](https://github.com/helloworld1/FreeOTPPlus/pull/219) but Catalan files are neither there nor in the master branch. 😕

**Comment by helloworld1** [comment]
Hmmm. Sorry I didn't double check it and thought the PR contains the change. @6543 is there a newer PR for the Crowin changes in Nov?

**Comment by 6543** [comment]
#228
