### ISSUE TITLE
Small visual bug: F-Droid continually fails to load the app icon on its app listing.

### ISSUE THREAD

**Issue by SC1040-TS2** [helloworld1/FreeOTPPlus#225]
This is something that is able to be replicated on F-Droid version 1.15.3. For some reason, while all other app icons seem to be loaded or eventually load in correctly on the app store, this one is one of the examples that is not.

While the cause of it is unknown at this time, possible incompatible icon file formatting, failing to target a newer Android SDK in terms of icon feature support, or simply something to do with how the app is packaged and listed in the app store may have something to do with it.

At the very least, this serves to bring up the existence of the problem as a small inconvenience for branding or what have you.

**Comment by helloworld1** [comment]
Thanks for letting me know. F-Droid used to be able to load the icon correctly. But now it doesn't. Not sure where the issue is.

**Comment by helloworld1** [comment]
I have refactored some configuration to using Google's recommended way and also updated SDK version to the latest. Hopefully it will work for the next version in F-Droid.
https://github.com/helloworld1/FreeOTPPlus/commit/6dfb9e2127a6746e4bb857ff85d8424b448eecfb
https://github.com/helloworld1/FreeOTPPlus/commit/54a2619fc6dd9681b7120b53a844aa75aaff4eb5

**Comment by SC1040-TS2** [comment]
> I have refactored some configuration to using Google's recommended way and also updated SDK version to the latest. Hopefully it will work for the next version in F-Droid. [6dfb9e2](https://github.com/helloworld1/FreeOTPPlus/commit/6dfb9e2127a6746e4bb857ff85d8424b448eecfb) [54a2619](https://github.com/helloworld1/FreeOTPPlus/commit/54a2619fc6dd9681b7120b53a844aa75aaff4eb5)

Hopefully, yes. However, I have also found another potential way of mitigating this as a personal thing.

In troubleshooting intermittent connectivity issues experienced over Wi-Fi in particular, with general icon, page and video loading, and video playback being affected, it was discovered that NewPipe was not quite ready for the upcoming F-Droid app indexing changes in F-Droid 1.6. Namely, its Upstream Repository will be deleted from F-Droid if one updates to the 1.6 Alpha build, seemingly preventing its self-update checks from working correctly and maybe breaking other app network functions as well.

Re-adding it using Method 2 restored the repo, and normal functionality with it. The necessary code refactoring, TargetSDK updating, and Gradle updates, however, will offer more tangible forms of seamlessness compared to what may be a placebo above. Just, uh, be ready for F-Droid 1.6.
