### ISSUE TITLE
Not possible to delete tokens

### ISSUE THREAD

**Issue by JKLs12** [helloworld1/FreeOTPPlus#229]
I can't find any possibility to delete wrong, old or unused tokens in the app. I tried swiping, long press, searched in the menu etc.
Is there really no possibility for such a basic task?

**Comment by helloworld1** [comment]
Click on the "..." on the right side of the token and select "Delete". I think I can also make long click to get the overflow menu also.

**Comment by JKLs12** [comment]
Oh, thanks. It's so easy when you know how. To be honest in my case I really needed you to tell me that. The problem is that I use dark theme/mode and with that it's nearly impossible to see the 3 dots. Even now where I know that they are there I can barely find them.
So a bit of colour adjustment would be good there I guess ;)

**Comment by helloworld1** [comment]
The "..." overflow menu looks fine in contrast on my phone in both dark and light theme.  In fact, I have tweaked its color in some recent releases. Let me just add long press there as an alternative.

**Comment by JKLs12** [comment]
I would show a screenshot to you but the app doesn't allow that. However, long press would be a great alternative. Just notice that long press is currently already in use for reordering (drag and drop).

**Comment by helloworld1** [comment]
Yea, you are right. Let me tweak the color again and see if it works better on your device.

**Comment by helloworld1** [comment]
I have this commit to tweak the color again https://github.com/helloworld1/FreeOTPPlus/commit/da3ae4ad3946efdd68f65083bdc89c67730a4498

<img width="370" alt="Screenshot_20221225_115024" src="https://user-images.githubusercontent.com/247316/209480398-a7946551-77b8-4776-b6ac-6de0edac28e9.png">
<img width="365" alt="Screenshot_20221225_115046" src="https://user-images.githubusercontent.com/247316/209480400-e96abc4b-43b9-42c4-af78-a9e252856957.png">
