### ISSUE TITLE
wrong code offset

### ISSUE THREAD

**Issue by CoenBeemer** [helloworld1/FreeOTPPlus#233]
Every time I enter a code it doesn't work, unless I wait 10-30 seconds(this fluctuates) AFTER the code expires on my phone. 
Is there a way to offset these codes so they work when they are  shown and don't when they're no longer shown? If there is, I haven't been able to find it.

I use the app on my pixel 7 with grapheneOs, app version 2.9
Hope someone can help!

**Comment by CoenBeemer** [comment]
The problem seems to be getting worse over time, I have to wait longer and longer until the otp works. First it worked fine, after a couple weeks I had to wait for the next otp to appear, another couple weeks and I had to wait for the next otp to expire halfway and now I can only enter my otp after the one after it has expired

**Comment by helloworld1** [comment]
Well, the TOTP will just calculate the time difference for the counter. If either your phone's time drifts or the server's time drifts, the TOTP will be in accurate. Seems like the clock on either your phone or on the server you authenticates further and further away so you need to skip one token. Would you try to make sure your phone's time sync is enabled and check that with your computer's time?

**Comment by CoenBeemer** [comment]
that aws indeed the issue, for some reason my phone's auto time sync was turned off after an update and it drifted causing TOTP's inaccuracy. Thank you for the solution!
