### ISSUE TITLE
Authentication not required after app loses focus

### ISSUE THREAD

**Issue by oyale** [helloworld1/FreeOTPPlus#234]
I recently set up authentication for FreeOTPPlus, but I noticed that the authentication is not required when the app has loses focus recently. 

**Steps to reproduce:**

1.    Enable authentication in the app's settings
2.    Press the home button or switch to a different app
3.    Reopen the OTP app and access OTPs without entering authentication.

**Expected behavior:**
The app should require authentication every time it is opened, regardless of whether it has lost focus.

**Actual behavior:**
The app does not require authentication when it is reopened after losing focus.

I think that this is a security issue that needs to be addressed as soon as possible.

 I appreciate your dedication to the project and understand that resolving this issue may take time and effort. Maybe is it using some timeout instead of watching for the focus? 
 
 If there is any additional information I can provide to help resolve this issue, please let me know. 

Thank you for your hard work and for making this app available as an open source project! :tada:

**Comment by helloworld1** [comment]
The app will only require authentication if you background and idle for about a minute. If you want to immediately lock, you can select "Quit and lock" in the overflow menu.

**Comment by helloworld1** [comment]
I have made the "Quick and lock" menu option as a toolbar icon to make it easier:
https://github.com/helloworld1/FreeOTPPlus/commit/da19264677b18d7b7d94e60d6910e82ebe282ca4

<img width="370" alt="Screenshot_20221225_115024" src="https://user-images.githubusercontent.com/247316/209480473-a5db2f89-7207-48e1-a890-0935218b0eb6.png">
