### ISSUE TITLE
[Bug] Dark mode - follow system

### ISSUE THREAD

**Issue by kudlav** [helloworld1/FreeOTPPlus#255]
Add option to "Follow system" dark/light theme.
System dark/light theme can be e.g. switched by plan, manually or after sunrise. The app should allow to follow the system theme.

https://developer.android.com/develop/ui/views/theming/darktheme#change-themes

**Comment by helloworld1** [comment]
I think it already supports follow system. If you uncheck the "Use dark theme" it will use the system theme

**Comment by kudlav** [comment]
If you uncheck "Use dark theme" it's always in the light theme.

Google Pixel 7a
Android 14
FreeOTP+ v3.0

**Comment by kudlav** [comment]
@helloworld1 please, reopen this issue

**Comment by helloworld1** [comment]
I tested this on the emulator and Galaxy S21 and FreeOTP 3.0. It follows the system fine after unchecking the dark mode option. Here is the commit for reference https://github.com/helloworld1/FreeOTPPlus/commit/f04a154640789918c2975b30f7351e81a67c540e

**Comment by kudlav** [comment]
Even after relaunching the app?

**Comment by helloworld1** [comment]
Yes, and actually you probably need to re-launch the app after you change the system theme.

**Comment by kudlav** [comment]
Then, this is not feature request, but a bug report:

1. Turn on System dark theme
2. Launch the app
3. Turn off Use dark theme
4. Relaunch the app
5. The app is always in light theme, not reflecting system theme.

Google Pixel 7a
Android 14
FreeOTP+ v3.0

**Comment by helloworld1** [comment]
I see. I reproduce it on Android 14, will take a look

**Comment by helloworld1** [comment]
I have fixed the issue in this commit: https://github.com/helloworld1/FreeOTPPlus/commit/5838e60cf6a2f0a7ba75f617419ce1485c684828

The fix will be released with the next version.

**Comment by PanderMusubi** [comment]
I was also wondering what the default is. Users need to switch system theme in order to find this out.

What common in apps is to explicitly offer this 1 of n select for Theme:
- System (default)
- Light
- Dark

Replacing the current check box with this will reduce confusion. Would you all support creating a new issue for this?
