### ISSUE TITLE
Any plans to update F-Droid and Google Play store out of date versions?

### ISSUE THREAD

**Issue by Filip-Anicic** [helloworld1/FreeOTPPlus#258]
Is there any plan to update and keep updated in the future, the app on these stores? Last update was on January 2023 and December 2022 on each respective store.
There is no other (convenient) way to keep the app up to date if there is a security update or something like that.

**Comment by helloworld1** [comment]
I have been testing latest changes. Will push out a release this weekend with the latest changes.

**Comment by helloworld1** [comment]
I have pushed out 3.1 release. Both Google Play and F-Droid will be updated in the following week or so.
