### ISSUE TITLE
Why has version 3.1 not been released for a long time?

### ISSUE THREAD

**Issue by SZ2528** [helloworld1/FreeOTPPlus#259]
Version 3.0 was released 1 year ago

**Comment by 6543** [comment]
@helloworld1 you have to make a release out of the tag i guess? to let the bots pick it up.

**Comment by helloworld1** [comment]
Ah I see. I tagged the it but forgot to create a release . Now I did it now.
However, I found F-Droid has already released the version 3.1
https://f-droid.org/en/packages/org.liberty.android.freeotpplus/
