### ISSUE TITLE
[Feature Request] Option to enable/disable 'Auto copy to clipboard'

### ISSUE THREAD

**Issue by itsKV** [helloworld1/FreeOTPPlus#26]
Dear developer, 
Every time we click on account to view the TOTP, it automatically copies the OTP to clipboard. 
There should be option to enable/disable this feature. This will prevent the OTP revealing to clipboard snooping apps running background. 

Kindly incorporate this feature.

**Comment by chepec** [comment]
I second this. Also, if you have many accounts, the popup obtrusively blocks the second-factor of the last one (bottom of the list) for the brief time it's visible (but it feels like forever ;-)
I was going to suggest moving the popup out of the way, perhaps on top of the app top-banner, but @itsKV suggestion may be even better.

Fantastic app, by the way. I really like how the numbers are hidden until they're requested, which significantly minimises clutter and removes the need to "pick the right one" out of a sea of numbers.

**Comment by helloworld1** [comment]
The issue could be fixed by this commit now: 5531ec6baf1b0ea6fe80d6e1923fc760f5d029ad

**Comment by helloworld1** [comment]
Well I don't think this issue is completely resolved. We still need an option to disable the clipboard copying. Reopening and will implement in the next release.

**Comment by helloworld1** [comment]
After this change a98597c369dedc23261e604962752479004bd7af, we have an option to not copy to clipboard now.
