### ISSUE TITLE
Add app icon to fastlane/f-droid

### ISSUE THREAD

**Issue by inson1** [helloworld1/FreeOTPPlus#261]

**Comment by helloworld1** [comment]
Any idea how to add. I think F-Droid should be automatically added it using the app icon.

**Comment by inson1** [comment]
@helloworld1 you have to add the icon here https://github.com/helloworld1/FreeOTPPlus/tree/master/fastlane/metadata/android/en-US/images
like
https://github.com/Darkempire78/OpenCalc/tree/main/fastlane/metadata/android/en-US

**Comment by helloworld1** [comment]
Thanks for the example. I have added the icon the same way. https://github.com/helloworld1/FreeOTPPlus/commit/5580c4413e088fcee9ae8449ec43b3576c6035a5
