### ISSUE TITLE
[Feature Request] Multiple Profiles / Token grouping

### ISSUE THREAD

**Issue by mariog0ncalves** [helloworld1/FreeOTPPlus#269]
Hi, before I start I'd like to thank everyone involved in this marvelous fork. The redhat's freeotp was already one of the best of it's kind, and your fork made it even better! It is by far one of the best out there. I don't know if this feature was already requested, I've searched it, but found nothing, so if it was sorry in advance. 

What I'd like to purpose was to have somehow the capability of grouping our tokens in separate "profiles", ie: Default and Work profile. Working nowadays as a software engineer on a big corporation has led me to use the app extensively besides  my personal day to day basis, and now I have work and personal tokens all mixed up. By search and looking at the email I can figure out which is which, but I thought this may be a good improvement to work on.

Best Regards.

**Comment by helloworld1** [comment]
I think implementing this issue https://github.com/helloworld1/FreeOTPPlus/issues/85 will satisfy your need.

**Comment by mariog0ncalves** [comment]
> I think implementing this issue #85 will satisfy your need.

Hi, yes you're completely right. Categorization/labelling of entries would fix my issue. Thank you
