### ISSUE TITLE
[Feature Request] Webdav Support with Automaical Syncronisation

### ISSUE THREAD

**Issue by schlagi123** [helloworld1/FreeOTPPlus#28]
Hi,

a very nice feature were the syncronisation to a WebDAV directory. This is nice for backup reasons or syncronisation, in you have multiple devices as second authenticator.

**Comment by strugee** [comment]
Can't this be done with the document provider support? If you install a WebDAV client that supports document providers you should be able to save there in FreeOTP+.

**Comment by helloworld1** [comment]
^ Correct. Thanks @strugee Document provider should do that.
