### ISSUE TITLE
Previously added keys disappear after import

### ISSUE THREAD

**Issue by kuba-orlik** [helloworld1/FreeOTPPlus#29]
Steps to reproduce:

1. Install app
2. Add a key
3. Import a previous backup

expected result:

the keys imported from backup and the key added in step 2 are available in the app

actual result:

only keys from the backup are available, and the key added in step 2 is missing. What's more, adding keys with QR code doesn't work

Deleting all app data solved the issue. I imported the backup first, and added keys later.

**Comment by helloworld1** [comment]
Yes, the JSON import will overwrite the current keys. Please use Key URI format to import / export so all current keys will be kept/

**Comment by kuba-orlik** [comment]
I think it would be nice if the app at least showed a warning about it when importing a JSON file

**Comment by helloworld1** [comment]
Yes, I hear you. I will see what I can do here.

**Comment by helloworld1** [comment]
I added an alert dialog to confirm when importing JSON and warn user the tokens will be cleared.
2d3e8943c0fac93af984f824420a965bffc85ad3
