### ISSUE TITLE
[Feature request] Export/Import to local storage

### ISSUE THREAD

**Issue by shezzski** [helloworld1/FreeOTPPlus#3]
I have found this application as I was searching for a way to Export/Import settings to local storage for FreeOTP.

It would be great if this app could write and read to/from a removable SD card in the phone for those security aware not wanting data in the cloud.

Great app otherwise!

**Comment by helloworld1** [comment]
You can export it to local storage. In the screen selecting storage location, click on the menu botton on the top right and select " Show internal storage", then you will be able to find the storage location in the drawer on the left.

There is currently a bug preventing importing from local storage. I will push out a fix soon.

**Comment by diogo-gomes** [comment]
@helloworld1, can you re-open this issue until the fix of importing from local storage?

Thanks
