### ISSUE TITLE
Proposal for standard data exchange format

### ISSUE THREAD

**Issue by fortran77** [helloworld1/FreeOTPPlus#30]
I don't know how active this project is, but if the developers are still working on it, please consider adding a standard data exchange format.

It would be as simple as:

One otpauth URI per line.

This URI format is already standard (see: [https://github.com/google/google-authenticator/wiki/Key-Uri-Format](https://github.com/google/google-authenticator/wiki/Key-Uri-Format)). All the TOTP applications already know how to parse it. So, for data exchange output, simply write one otpauth URI per line to an output file. On input, read one line at a time and parse it as an otpauth URI.

At least one developer may be willing to go along with this if others do: [https://github.com/Authenticator-Extension/Authenticator/issues/282#issuecomment-464501532](https://github.com/Authenticator-Extension/Authenticator/issues/282#issuecomment-464501532).

**Comment by helloworld1** [comment]
Not very active for now but at least not dead. Is the otpauth URI commonly used today? 
Also do you want just an import function or also include export function using the otpauth URI?

**Comment by fortran77** [comment]
Every time any Authenticator app scans a QR code, it is reading an otpauth URI and parsing its fields. So the hard work is already done.

The idea here is for different TOTP-type applications to be able to exchange data. So you would need both export and import. People often use more than one, e.g., one on a desktop, one on a smartphone. Or they may need to migrate from one to another in case one is abandoned by its developers which, let's face it, does happen now and then.

**Comment by fortran77** [comment]
One benefit of having a line-by-line export format would be that a user could edit the exported file with a text editor to add or remove lines before importing it into another application.

**Comment by helloworld1** [comment]
Sounds like a good idea and shouldn't be hard to implement.

**Comment by fortran77** [comment]
Our colleagues at one other project have come through amazingly quickly and have written the code already for this proposal; see: [https://github.com/Authenticator-Extension/Authenticator/issues/282#issuecomment-465022079](https://github.com/Authenticator-Extension/Authenticator/issues/282#issuecomment-465022079). This is very exciting. If two projects (FreeOTP+ and theirs) adopt this common data exchange format, then everybody else is likely to come on board too.

**Comment by fortran77** [comment]
Our colleagues have not only finished implementing the standard one-url-per-line backups format, but also have a web page describing it:

https://github.com/Authenticator-Extension/Authenticator/wiki/Standard-OTP-Backup-Format-Devloper-Info

**Comment by helloworld1** [comment]
@fortran77 
We are implementing the standard format now. 
Other than the text file. Do we also need to support share through intent on Android? With that, you can share with intent of single item like otpauth://totp/example.com?secret=FLIQ7AABIXF2DBUYE7VYAV2T7232KVYB to other app or receive intent with the same format.

**Comment by fortran77** [comment]
First of all, thanks for doing this.

Exporting only to a local text file provides some security against careless use. But it will also make it a bit harder for the user to exchange data across devices, e.g., between Android and IOS, or to/from the desktop.

So I think a good compromise would be to allow sharing via intents on Android, but warn the user clearly that the exported data are unencrypted. That way a user with an end-to-end secure messaging app (like Wire or Signal) can still send the exported file securely and everybody else knows to be cautious.

I don't see any harm in being optionally able to share a single entry, though of course the original idea was to export all entries.

By the way, nobody has thought about what to do with duplicates on import. It should be safe to ignore multiple identical entries, but what if the secrets match but other parts of the record differ? It's an open question.

**Comment by clach04** [comment]
👍 

This would be a great enhancement.

I've been sitting a little script for dumping pins secrets for exported from FreeOTP+. Finally posted it to https://github.com/clach04/pyFreeOTPPlus/ - it basically has the URL generation in there (as part of the code for generating google chart qrcodes with those URLs.

I would definitely use/prefer the newer URL export format over the signed-integer array format.

No rush as I have a solution but I'm looking forward to this new feature :)

**Comment by fortran77** [comment]
I just figured this out:

> It should be safe to ignore multiple identical entries, but what if the secrets match but other parts of the record differ? It's an open question.

I have in fact encountered situations where two or more entries had identical secrets, when a website could be accessed two different ways. For example, you can access Skype at skype.com or at one of the Microsoft domains. You will eventually enter the same login/password/2FA for both types of logins, but you might still want separate login entries for both.

So the answer is simple: Cast out only identical duplicates, and retain multiple different entries even if the secrets match.

**Comment by helloworld1** [comment]
Key URI format is supported in this commit: 5eed374b7aaa0ae6cdda38ecb89af65d09756879

**Comment by mymindstorm** [comment]
I'm one of the maintainers of Authenticator Extension. I want to keep a list of all programs that support the format on [this page](https://authenticator.cc/docs/en/otp-backup), is it ok if I add FreeOTP+ to it?

**Comment by helloworld1** [comment]
Yes, please feel free to add FreeOTP+ 1.3+ as supported client of standard format. It should be fully supported. If there are any interoperability problems, please create a new issue.

**Comment by pepa65** [comment]
> Our colleagues have not only finished implementing the standard one-url-per-line backups format, but also have a web page describing it:
> 
> https://github.com/Authenticator-Extension/Authenticator/wiki/Standard-OTP-Backup-Format-Devloper-Info

This page no longer exists...

**Comment by mymindstorm** [comment]
Not gone, just moved: https://authenticator.cc/docs/en/otp-backup-developer

On Jan 24, 2023, at 11:08 PM, pepa65 ***@***.***> wrote:

﻿

Our colleagues have not only finished implementing the standard one-url-per-line backups format, but also have a web page describing it:

https://github.com/Authenticator-Extension/Authenticator/wiki/Standard-OTP-Backup-Format-Devloper-Info

This page no longer exists...

**Comment by pepa65** [comment]
I'm working to get the `twofat` CLI totp manager on board with this, will let you know once it's done.

**Comment by helloworld1** [comment]
Great to see the effort is still ongoing. The interop between OTP apps should be easy and effortness. FreeOTP+ 3.0 has introduced the directly sharing one token to other apps without importing / exporting. I feel the some multi-line schema would be helpful to  share as intent to other apps too.

**Comment by pepa65** [comment]
@mymindstorm Released `twofat` with OTPAUTH_URI import & export:
https://github.com/pepa65/twofat
