### ISSUE TITLE
Add a token with 7 digits

### ISSUE THREAD

**Issue by emericv** [helloworld1/FreeOTPPlus#33]
Hello, It's not possible to add a token with and 7 digits codes (used with some services).
Thanks in advance :)

**Comment by emericv** [comment]
Similar issue onkeepassxc to illustrate: https://github.com/keepassxreboot/keepassxc/issues/1762

**Comment by helloworld1** [comment]
This commit adds 7 digits token; 64734372229ce2bb7b468c11fe4fc14ffa40d0c5
