### ISSUE TITLE
Toast notification temporarily blocks last entry

### ISSUE THREAD

**Issue by oxr463** [helloworld1/FreeOTPPlus#35]
I have several entries for two-factor and when I tap the last one to reveal the code, the toast notification pops up in front of it. It's not a huge deal, just a minor annoyance.

**Comment by helloworld1** [comment]
I can change it to snack bar so it won't overlap with others apps.

**Comment by oxr463** [comment]
Oh excellent!

**Comment by helloworld1** [comment]
The issue is fixed in this commit: 5531ec6baf1b0ea6fe80d6e1923fc760f5d029ad
