### ISSUE TITLE
Trying to import image (e.g. QR code) causes app to crash

### ISSUE THREAD

**Issue by MalikKillian** [helloworld1/FreeOTPPlus#42]
I was hoping this was a feature but instead I found out the app crashes if you try and import a PNG image.

**Comment by helloworld1** [comment]
I tested PNG image is fully working on my phone and emulator. I wonder if the app crashes on every png image or only specific ones. If it only happens on specific ones, would you attach a png image here? thanks!

**Comment by wischi-chr** [comment]
Accidentally selected a gif and it crashed for me to. Maybe just an error (snackbar) should be shown instead of crashing.

**Comment by helloworld1** [comment]
I see you are trying to import image not token text files. Ideally the document provider will filter out the invalid files but additional checks should also be there.

**Comment by helloworld1** [comment]
Closing the issue after multiple upgrade to the jetpack camera library
