### ISSUE TITLE
[Feature request] Transparency support in image of account's logo

### ISSUE THREAD

**Issue by m-alice** [helloworld1/FreeOTPPlus#44]
Now, transparent background just replaced to black color

**Comment by helloworld1** [comment]
If you uses a PNG image with transparent background, FreeOTP+ will respect that. The JPG won't have transparent background.

**Comment by m-alice** [comment]
Please, take a look.
[icons.zip](https://github.com/helloworld1/FreeOTPPlus/files/3355821/icons.zip)

**Comment by wjoe** [comment]
@helloworld1 This isn't correct. Transparent PNG images show black instead of a transparent background, as the original poster described.

**Comment by helloworld1** [comment]
Yes, I am able to reproduce the issue on the Android 7.1 emulator. Not sure why some PNGs are displaying black background.

**Comment by error401de** [comment]
I have the same issue with the black background on transparent images. Is there any chance to fix this?

**Comment by helloworld1** [comment]
Yes, for sure. Will need to investigate further. There could be a simple fix.

**Comment by error401de** [comment]
Could be fixed with https://github.com/helloworld1/FreeOTPPlus/pull/70 :)
