### ISSUE TITLE
Account information in darkmode / low light are hard to read

### ISSUE THREAD

**Issue by bonjour81** [helloworld1/FreeOTPPlus#45]
Hello!
When in darkmode and low brightness (at night) it's very hard to read the accounts information written in black over dark grey. 
Maybe account information should be in brighter color over dark grey background,like the 6 digit code.

**Comment by helloworld1** [comment]
Current FreeOTP+ is using default theme's color for the text for both light and dark theme. Personally I found it fine. But I can fine tune the contrast a bit.

**Comment by bonjour81** [comment]
Hi!
I assume It may depends on smartphone model.
On my side it's an issue only at minimum brightness,when I want to use it in the dark.
It's perfectly readable during day.

**Comment by ExpandingFoam** [comment]
I agree. Dark grey on medium grey is not ideal. 

![2019-07-07-17 01 05 377](https://user-images.githubusercontent.com/51429315/60773823-3770d680-a0d9-11e9-908f-46f7405657e4.jpeg)

**Comment by rugk** [comment]
Also saw the menu issue. BTW, FYI, @ExpandingFoam, [here is how to take a screenshot on Android](https://www.take-a-screenshot.org/android.html). :smiley:

**Comment by ItsExtra** [comment]
@rugk thank you. :) However I was trying to share how it appears on my display, from the outside. A screenshot might look fine. Presumably on some displays it does, or it wouldn't have been designed that way. 

I think the photo did the job I wanted it to.

**Comment by helloworld1** [comment]
Yea, that looks very hard to see. I think I have fixed the issue in this commit: https://github.com/helloworld1/FreeOTPPlus/commit/5991c3e3238e0d34fb66ad408b383de899187aba

I just didn't release that version. I should release soon.

**Comment by ItsExtra** [comment]
@rugk thank you. :) However I was trying to share how it appears on my display, from the outside. A screenshot might look fine. Presumably on some displays it does, or it wouldn't have been designed that way. 

I think the photo did the job I wanted it to.

**Comment by helloworld1** [comment]
I can try to publish 1.5 update this week and you can try and see if there are any improvement. 
Maybe I can you pure black for background also.

**Comment by helloworld1** [comment]
I have released version 1.5 with a new fix cd4b5751be6f72d7757b249f4717f3a7e1e3c356 to improve the contrast of the overall contrast for each token card. I am closing this issue. Please feel free to reopen if the contrast is still a problem.
