### ISSUE TITLE
how/do backups work?

### ISSUE THREAD

**Issue by ExpandingFoam** [helloworld1/FreeOTPPlus#47]
Hi, 

I would like to switch from Authy to a floss product. However I am worried that if I lose my phone I will be SOL. 

I just installed FreeOTP+ on my phone. I added 1 account to it. If I make a backup now, then add 3 more accounts, will my original backup be able to communicate with all 4 accounts? Or do I need to backup each time I add an account?

What is the difference between exporting json and URI format? Does it matter? I see they can both be imported, so maybe it doesn't. 

Also what is the function of "Add Token"?

I am not a computer programmer or any related profession so sometimes I miss things that seem obvious to those in the industry.

**Comment by helloworld1** [comment]
1. You will need to manually export backup file each time you add / change account
2. Both JSON and URI format works fine. Some other OTP apps can read URI format while only FreeOTP+ can read JSON format.
3. For "Add token", if you happen to know the token secret, you can add token without scanning QR code. It is basically the same as QR code method. If you are not expert, probably you won't use it.
