### ISSUE TITLE
How to add Steam?

### ISSUE THREAD

**Issue by OLLI-S** [helloworld1/FreeOTPPlus#48]
Is it also possible to add the Steam Autheticator token to FreeOTP+?
If yes, how?

**Comment by helloworld1** [comment]
Yes, it is supported though obsecure.  It requires some manual work to transfer secret from Steam guard to FreeOTP+.
Here are some insights on how to get secrets from Steam guard.
https://github.com/hyt47/SteamDesktopAuthenticator-Mod-47/wiki/Manually-import-your-Steam-Account-from-Android
Once done, make sure the "Issuer" in FreeOTP+ is "Steam".

This is the commit to support:
https://github.com/helloworld1/FreeOTPPlus/commit/508e16e6cdd106157a07dfabdda8e45c05abe42c

**Comment by synthead** [comment]
Can this be done without a rooted phone?

**Comment by kepi** [comment]
For those who are not wise from above post :) it is pretty simple to add, if you have rooted phone.

### Step 1 - Getting your secret

In directory `/data/data/com.valvesoftware.android.steam.community/files/` there is file named like `Steamguard-YourSteamID64Code`. Just open it in root explorer, adb or any tool capable of reading text files. It is json file, and you need value of `url` field, which will look something like this: `"uri": "otpauth://totp/Steam:yoursteamlogin?secret=ABCDEFGH1234567890&issuer=Steam"`

The part between `secret₌` and `&issuer=` is what you need.

### Step 2 - Adding token in FreeOTPPlus

Click *Add Token* and set fields like this:

- **Issuer:** Steam
- **Account:** your account name (this is just name so you recognize it)
- **Secret:** the secret from previous step
- **Type:** TOTP
- **Digits:** 5
- **Algorithm**: SHA1
- **Interval:** 30

and you are done

**Comment by helloworld1** [comment]
Thanks a lot for the instruction for adding steam code!
