### ISSUE TITLE
Question about issue FreeOTP 

### ISSUE THREAD

**Issue by ghost** [helloworld1/FreeOTPPlus#5]
hello thank you for your work with this freeotp fork.
I have a few questions:
1. https://github.com/freeotp/freeotp-android/issues/172 you know something about this bug. It seems to work well with your Plus version, you confirm me
2. Since when do you work with this fork you have plans for the future.
3. The original version has been abandoned or will be further developed.

Thanks again for the fork, just yesterday I was trying out the original version, it was giving me problems with everything (qr images etc...)

**Comment by helloworld1** [comment]
1. I can reproduce the crashing bug you linked in plus version also. I will analyze and fix it in the next version.
2. I have been working with this fork for more than a year or so. I don't have much plan other than small improvement or bug fixes.
3. I don't think the original maintainer are still working on the FreeOtp. It haven't been updated for more than two years.
