### ISSUE TITLE
Export and import on another device (not sure it's an issue)

### ISSUE THREAD

**Issue by atrent** [helloworld1/FreeOTPPlus#52]
I'm trying to export tokens form one device to import them on another device to have two OTP generators (they should work in parallel, one as a backup of the other). I have github and gitlub tokens active, but when imported (successfully) on the second device the OTP generated by the second device is not valid for login on gitlab.
Am I doing something wrong? Is there some part of seed/secret that is not exported?
Thank you

**Comment by atrent** [comment]
[solved]
my second device is a VM on QEMU and the time was set to UTC instead of CEST (mine), used '-rtc base=localtime' as an option in QEMU and now the two OTP are perfectly in sync, I'm closing this issue.

**Comment by helloworld1** [comment]
Glad you figured out. Right, the token is time dependent..
