### ISSUE TITLE
Unable to scan QR, image looks distorted, bad aspect ratio

### ISSUE THREAD

**Issue by gemarcano** [helloworld1/FreeOTPPlus#57]
OnePlus 6's camera, as far as I can tell, defaults to a 4:3 aspect ratio. This seems to confuse this app. Interestingly enough, the original FreeOTP does not have this problem. I've attached a screenshot of what's supposed to be a square.
![Screenshot_20191012-232554](https://user-images.githubusercontent.com/4000062/66710494-c3814280-ed47-11e9-82c7-a5f09fe35ed4.jpg)

**Comment by helloworld1** [comment]
Feels like Google'a CameraX's compatibility issue. Let me check on Google side.

**Comment by opensam** [comment]
Xiaomi phone here. Android 9. Kernel 4.4.
Very similar issue : unable to scan a QR code because of bad aspect ratio.
With another QR scanner it is ok : I see a square border.
With FO+ it doesn't work : I see a rectangle (higher than wide, like a tower).

**Comment by fabermundi** [comment]
Same thing here with a Motorola Moto X4

**Comment by BugProg** [comment]
I have the same problem with my One Plus 5t

**Comment by helloworld1** [comment]
I updated CameraX, and there are some options I can tweak. I will work on that and build a version to see if it works to keep the aspect ratio.

**Comment by helloworld1** [comment]
I am aware of this issue. I have tried to fix the issue with commit 564753f It would be great if anyone can test before I make a release.  Personally I have no issues with Pixel phones and Huawei Mate 10 pro  with Android 9.

You can download a debug APK to test if you cannot compile: https://drive.google.com/file/d/1hf-zu2ZuaC5DYaNinHENDsRGOZzjwAbn/view?usp=sharing
The debug app will NOT replace your stable release app. The app name will be "FreeOTP+ Debug"

**Comment by helloworld1** [comment]
Closing this issue since I have heard back the latest master works fine now.
