### ISSUE TITLE
Unable to scan QR code after update

### ISSUE THREAD

**Issue by pasha132** [helloworld1/FreeOTPPlus#58]
Hello!
After update 1.4 to 1.5 QR-code scanner unable to detect qr. App runs camera with scan-region but didn`t see any codes: 1.4 works perfectly on same conditions.
I have Huawei Nova:
```
Android Version: Android 7, latest official firmware, no root
Device manufacturer: Huawei
Device model: Nova (CAN-L01\L11)
```

**Comment by tpapp** [comment]
I am experiencing the same issue, Xiaomi Mi A2 Lite, Android 9, no root.

**Comment by helloworld1** [comment]
I am aware of this issue. I have tried to fix the issue with commit 564753f8f2d13f361ff353d1789a101d105e165c

It would be great if anyone can test before I make a release. Personally I have no issues with Pixel phones and Huawei Mate 10 pro with Android 9.

**Comment by helloworld1** [comment]
You can download a debug APK to test if you cannot compile: https://drive.google.com/file/d/1hf-zu2ZuaC5DYaNinHENDsRGOZzjwAbn/view?usp=sharing

The debug app will NOT replace your stable release app. The app name will be "FreeOTP+ Debug"

**Comment by pasha132** [comment]
Hi! Latest version from master branch works on my device. Thank you.

**Comment by helloworld1** [comment]
Thanks for the feedback! Closing the issue now.
