### ISSUE TITLE
exits camera immediately when trying to scan QR code

### ISSUE THREAD

**Issue by KlavsKlavsen** [helloworld1/FreeOTPPlus#66]
I tried with some barcodescanner app - and it stays in the camera without issues.
In FreeOTP it just shows the camera for a brief second - and then exits and goes back.. :(

Anything I can do to debug?

**Comment by KlavsKlavsen** [comment]
I tried downgrading to 1.5 - but it just says it failed to downgrade due to "unknown error" :(

**Comment by vikingtiger** [comment]
This seems to be duplicate of #60. @helloworld1 posted a link to a debug build there which appears to solve the problem.

**Comment by helloworld1** [comment]
Close for duplicate #60 Thanks @vikingtiger  for mentioning
