### ISSUE TITLE
Contribute back to FreeOTP

### ISSUE THREAD

**Issue by mueller-ma** [helloworld1/FreeOTPPlus#7]
Hey @helloworld1,
can you contribute those features back to https://github.com/freeotp/freeotp-android?

**Comment by samphunter** [comment]
There is a reason export feature is not part of most OTP apps. Allowing export allows anyone you borrow your phone to for a few minutes to copy your tokens without you even knowing. Not allowing export was a conscious decision and that is why this can't pushed to Free OTP. Also this app should really warn users about the security tradeoff this feature has.

**Comment by helloworld1** [comment]
Yes, it is true, I think this does make the security worse that a person could export and view all the 2FA secrets without rooting your phone if he gain access to the phone.

Well, it is a trade off for convenience especially for those who frequently changes phone and have a lot of 2FA code to migrate. 

Probably I can add a PIN lock screen and also fingerprint access to the app. The PIN can also be used to encrypt all the credentials.

**Comment by daniel-illi** [comment]
@helloworld1IMO this is a great idea. A fingerprint lock does not lessen convenience much, but keeps the casual attacker away 🙂

**Comment by aimanbaharum** [comment]
> Probably I can add a PIN lock screen and also fingerprint access to the app. The PIN can also be used to encrypt all the credentials.

Make this a priority pretty please 😄
