### ISSUE TITLE
请求加入本地化，以及从Google Authenticator导入数据，定时备份令牌到云盘的功能。

### ISSUE THREAD

**Issue by daiaji** [helloworld1/FreeOTPPlus#74]
其他的都很好了
这几项应该挺急需
云盘用常用的那些就完事了……
手机导入导出令牌挺麻烦的
万一忘了备份令牌，手机丢了，或者坏了，两步验证就死翘翘了……
直接导出到网盘可以说是很重要了，除了常用的网盘支持外，可以加入WEBDAV服务器。这样也能导入到自己的服务器了。
定时同步应该也挺重要的，怕忘记导出……
Google Authenticator有源码，数据位置，数据结构应该能搞清楚，可能需要root吧，没root就当没有这功能就行了，或者能够通过adb shell的权限弄到数据？真想导出Google Authenticator的数据的话应该不会介意开电脑……
本地化有助于更好的用户体验……

**Comment by ce-4** [comment]
Hi @daiaji it would help if you write in english, the yandex/google translation is not very accurate unfortunately. From the inaccurate translation you seem to be asking about Google Authenticator export function - but this is FreeOTPPlus and it already has an import/export function.

**Comment by helloworld1** [comment]
1. FreeOTP+ supports Google's document framework so if you have installed Webdav app that exposes document API, FreeOTP+ can use it directly.
2. I think scheduled backup could be a good idea. Maybe we should just expose a Tasker or any open sourced alternative interface so other app can schedule the backup
3. Google has only open sourced very old version of Google authenticator. I don't think it would be easy to import from Google Authenticator.

**Comment by daiaji** [comment]
>     2. I think scheduled backup could be a good idea. Maybe we should just expose a Tasker or any open sourced alternative interface so other app can schedule the backup
I am concerned about the reliability of this solution ...
>     3. Google has only open sourced very old version of Google authenticator. I don't think it would be easy to import from Google Authenticator.
Google doesn't seem to be that great.

**Comment by ce-4** [comment]
There is localization, however only italian and another language.

You can translate it and create a pull request:
https://github.com/helloworld1/FreeOTPPlus/blob/master/app/src/main/res/values/strings.xml

**Comment by 6543** [comment]
@daiaji feel free to use https://crowdin.com/project/freeotpplus - I'll submit create pull's from there

**Comment by helloworld1** [comment]
Thank for @6543 for providing crowdin option for localization. Closing this issue since other requests are not actionable for now.
