### ISSUE TITLE
Prevent screenshots for security reasons

### ISSUE THREAD

**Issue by ralfbergs** [helloworld1/FreeOTPPlus#75]
I would like to suggest using the flag [FLAG_SECURE](https://developer.android.com/reference/android/view/WindowManager.LayoutParams.html#FLAG_SECURE) to prevent malicious apps from creating screenshots to steal OTP codes.

**Comment by fe60** [comment]
Just searched the existing code:
https://github.com/helloworld1/FreeOTPPlus/blob/master/app/src/main/java/org/fedorahosted/freeotp/ui/MainActivity.kt#L110

**Comment by helloworld1** [comment]
Not sure why it is commented out. We should have it enabled. Thanks!

**Comment by helloworld1** [comment]
This commit has fixed the issue https://github.com/helloworld1/FreeOTPPlus/commit/40d36d8bf69db057a8641562f868ee3674d3f43a
