### ISSUE TITLE
improve security by blocking screenshots

### ISSUE THREAD

**Issue by altiOnGithub** [helloworld1/FreeOTPPlus#76]
Hello,

please don't permit screenshots in the app since these might contain OTP codes.

The FLAG_SECURE code part seems to be already present but is currently commented out in:
https://github.com/helloworld1/FreeOTPPlus/blob/a98597c369dedc23261e604962752479004bd7af/app/src/main/java/org/fedorahosted/freeotp/ui/MainActivity.kt#L111

for context also see:
https://www.zdnet.com/article/google-could-have-fixed-2fa-code-stealing-flaw-in-authenticator-app-years-ago/

Thank you very much!

**Comment by altiOnGithub** [comment]
sorry for the duplicate - https://github.com/helloworld1/FreeOTPPlus/issues/75
please decide yourself which one to work with .. THX!

**Comment by helloworld1** [comment]
Not sure why it is commented out. We should have it enabled. Thanks!

**Comment by helloworld1** [comment]
This commit has fixed the issue https://github.com/helloworld1/FreeOTPPlus/commit/40d36d8bf69db057a8641562f868ee3674d3f43a
