### ISSUE TITLE
Crash on Galaxy S5 Stock ROM

### ISSUE THREAD

**Issue by FabriceSalvaire** [helloworld1/FreeOTPPlus#78]
Trying to scan a QR code on a  Galaxy S5 Stock ROM, camera is out of focus and it crashes

**Comment by seventer** [comment]
Same here. Using FreeOTP+ Version 1.8(9) When scanning QR on a Lenovo K10a40 the app crashes.

**Comment by helloworld1** [comment]
I will update to the latest version of Jetpack CameraX library to see if it resolves the problem.

**Comment by seventer** [comment]
That would be awesome. Please let me know when to test the new version.

**Comment by helloworld1** [comment]
Please try version 1.9 that is updated with more phone camera support. I don't have galaxy s5 so I will rely on users to test out.

**Comment by seventer** [comment]
My Lenovo K10a40 is working fine now. No crashes anymore. Thanks for the update!

**Comment by helloworld1** [comment]
Thanks for reporting back. Closing the issue.
