### ISSUE TITLE
Now that Google Auth has an export feature, could we import their tokens from FreeOTP+ ?

### ISSUE THREAD

**Issue by jdevora** [helloworld1/FreeOTPPlus#79]
The latest version of the Google Auth app added a functionality to export tokens to another phone scanning a QR code.

I tried to scan this code from FreeOTP+ but it doesn't recognize it.

Could we add the ability to import tokens using Google Auth's export QR?

**Comment by helloworld1** [comment]
I don't understand the format at all. Without the understanding, I am unable to import the token.

This is the original token
Issuer: AAAAA
Account: bbbbbb
Secret: ivw37pcvqu2yaahovbxqws6j25adxa6yr2qczqevxabbadmtpvrmzu5b


This is google's format:
otpauth-migration://offline?data=CjsKI0Vtv7xVhTWAAO6obwtLyddAO4PYjqAswJW4AhANk31izNOhEgxBQUFBQTpiYmJiYmIgASgBMAE4AhABGAEgACiKzs7%2B%2Bv%2F%2F%2F%2F8B

**Comment by m4rkusxxl** [comment]
This project may help:
https://github.com/dim13/otpauth

The data is a urlencoded and base64 encoded protobuf with this format: https://github.com/dim13/otpauth/blob/master/migration/migration.proto
