### ISSUE TITLE
Import from lastpass authenticator

### ISSUE THREAD

**Issue by ejortegau** [helloworld1/FreeOTPPlus#80]
Lastpass authenticator is nice and works, but it's closed source run by a company looking to make money. I'd like to migrate from it to FreeOTP+. Since lastpass authenticator backs up, I would like to be able to import from such backup into FreeOTP+

**Comment by helloworld1** [comment]
I wonder what is the format of LastPass backup. Also are you able to export as csv file like this https://support.logmeininc.com/lastpass/help/how-do-i-export-stored-data-from-lastpass-using-a-generic-csv-file ?

**Comment by mattcen** [comment]
As far as I know, while you can export passwords from LastPass, there is no way to export OTP keys from LastPass Authenticator (while they can be backed up to LastPass, I'm aware of no tool besides LastPass Authenticator that can retrieve that backup). I avoided this problem by generating OTP keys for FreeOTP+ *first* and then I could export those and generate QRcodes to scan into LastPass Authenticator if I wanted to. It's a bit of a pain to migrate manually, but it may be your only choice.

**Comment by helloworld1** [comment]
Closing this issue due to closed source nature of LastPass.

**Comment by bzy39** [comment]
found this.
https://blog.unauthorizedaccess.nl/2021/03/07/export-totps-from-lastpass-authenticator.html
https://github.com/dmaasland/lastpass-authenticator-export
