### ISSUE TITLE
Steam one time token has an extra char

### ISSUE THREAD

**Issue by heinrich5991** [helloworld1/FreeOTPPlus#82]
Steam one time tokens seem to be 5 characters long, not 6. It was only possible to select 6, 7 or 8 characters for the token when importing.

E.g. it displays M3FCC4, but the correct token is the prefix M3FCC. I tried both the 5 char prefix (works) and the whole token (doesn't work).

**Comment by heinrich5991** [comment]
Thanks for making this app, by the way. It's really useful. :)

**Comment by helloworld1** [comment]
Would I adding a 5 digits option for the "Add token" screen work?

**Comment by heinrich5991** [comment]
If that would give me the 5 char prefix of the 6 char token, then yes, that's exactly what I want. :)

**Comment by helloworld1** [comment]
I personally don't have steam 2FA. I can make the change and build an APK for you to test out before committing.

**Comment by heinrich5991** [comment]
Sure, will be happy to test.

**Comment by helloworld1** [comment]
Please try this debug build. It won't overwrite your release build from Google play. The app name is "FreeOtp+ Debug". Please add your Steam token, issuer -> "Steam", Digits -> 5. If it works, I will commit this change.

https://drive.google.com/file/d/1_a3RQne537S7yRgmnjJv4-BcjrBjJVrC/view?usp=sharing

**Comment by heinrich5991** [comment]
I cannot download the link, it seem to be private.

**Comment by helloworld1** [comment]
Please try again. Sorry about that.

**Comment by heinrich5991** [comment]
Works great! Thanks for the quick fix!

**Comment by heinrich5991** [comment]
Is this going to get implemented in the main branch? I don't see commits doing this.

**Comment by helloworld1** [comment]
Sorry forgot to check it in before closing it. It is here: https://github.com/helloworld1/FreeOTPPlus/commit/470e8dca74a81d791efff748d9ac89fb9839a0d2
