### ISSUE TITLE
Nextcloud provider is not listed in export dialog

### ISSUE THREAD

**Issue by poiNt3D** [helloworld1/FreeOTPPlus#9]
I'm using Nextcloud. Other apps show it in open or save dialogs.
When i select Export there is just Recent, Downloads, Internal Storage and SD card.

**Comment by helloworld1** [comment]
The provider needs to be integrated with Google's Document provider framework. If you go to "Files" app on Android 8.0+, you can see all the providers. I believe if Nextcloud is not showing in the export dialog, it is not integrated with Document framework.
