### ISSUE TITLE
Enable AutoUpdate to F-Droid

### ISSUE THREAD

**Issue by 6543** [helloworld1/FreeOTPPlus#90]
keep it open until progress done at AutoUpdate ...

*this issue is more for documentation purpuse*

Links:
 * https://gitlab.com/fdroid/fdroiddata/-/merge_requests/7229 (Enable AutoUpdate for FreeOTP Plus)
 * https://gitlab.com/fdroid/fdroiddata/-/merge_requests/7293 (Update FreeOTPPlus) <- add 1.9 and 2.0

**Comment by 6543** [comment]
Update: [!7293](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/7293) got merged ...

**Comment by helloworld1** [comment]
Published version 2.1 to test out the AutoUpdate process on F-droid. Let me know if commit https://github.com/helloworld1/FreeOTPPlus/commit/587cfc9010cfcb5c76a4de07a85caf98f594b169 is enough to trigger auto update.

**Comment by helloworld1** [comment]
It seems like the 2.1 is not auto updated in F-droid.

**Comment by 6543** [comment]
not yet - still disabled

https://gitlab.com/fdroid/fdroiddata/-/merge_requests/7229 was not merged jet

I'll have a look later ...

**Comment by 6543** [comment]
submited own ... lets see how it is going https://gitlab.com/fdroid/fdroiddata/-/merge_requests/7411

**Comment by 6543** [comment]
auto update worked: https://gitlab.com/fdroid/fdroiddata/-/commit/8b4fc728992c0035be4a6d70373c347e27cf55d8

**Comment by helloworld1** [comment]
The version 2.1 still doesn't seem to be published in F-Droid. Does it fail to build? I am not familiar how to find what was going wrong.
