### ISSUE TITLE
Provide a way to remove an image

### ISSUE THREAD

**Issue by wischi-chr** [helloworld1/FreeOTPPlus#93]
It should be possible to remove an image and switch back to the image provided by the heuristic.

**Comment by helloworld1** [comment]
Yea, there is no way to remove a image for now. Will provide a button or something to remove the icon.

**Comment by helloworld1** [comment]
The feature is added in this commit: https://github.com/helloworld1/FreeOTPPlus/commit/e0b503ff0fe6b6caec05f7abc7b01d821d921582
