### ISSUE TITLE
NFS Burner - Request

### ISSUE THREAD

**Issue by 7uppi** [helloworld1/FreeOTPPlus#98]
Would it be possible to incorporate a NFC burner to burn cards like [these](https://www.protectimus.com/protectimus-slim-mini/) from the APP?

Thanks.

**Comment by helloworld1** [comment]
Unfortunately I don't have any of those to test. Would be great if anyone who has the cards to contribute.

**Comment by 7uppi** [comment]
Well, I don't have that much coding experience (if you can even say I have any), but you have to start somewhere right.
I will try to find some time and see if I can learn some stuff.

**Comment by helloworld1** [comment]
Closing since we don't have it is a common use case.
